### PR TITLE
Clearer approach to Zookeeper scroll

### LINKED ISSUE #9579: [BUG]: Scrolling not possible in TTC panel while text is being generated
### Describe the bug

https://github.com/user-attachments/assets/d1ab6b42-81e8-46e7-87e2-f80c1c844cda

### Steps to Reproduce

1. generate multiple TTC messags
2. try to scroll up to get some previously written text

### Expected Behavior

New TTC thinking messages should not move the window but the thinking sub-window should continue to scroll for updates

### Screenshots and Recordings

_No response_

### Desktop OS

-

### Browser

_No response_

### Version

1.1.4

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by pierremtb**
Fixes #9579

What we agreed on as a systematic approach at https://github.com/KittyCAD/modeling-app/issues/9579#issuecomment-3724312489:

> 1. the Reasoning view should always autoscroll
> 2. the Conversation view should never autoscroll
>   a. however, on prompt submit, force a scroll to the bottom of the conversation to show the prompt and the placeholder for response
> 3. (polish for later) any new message hidden from view in the conversation view should show a little badge like Slack, Messenger, et al that says "Jump to new messages" or something

This PR only handles 1, 2, and 2a, which is sufficient to fix #9579.

### CODE REVIEW

File: src/components/MlEphantConversation.tsx [hunk 1]
```diff
@@ -288,37 +288,24 @@ const StarterCard = ({ text }: { text: string }) => {
...
+      requestAnimationFrame(() => {
+        if (refScroll.current) {
+          refScroll.current.scrollTo({
+            top: refScroll.current.scrollHeight,
+            behavior: 'smooth',
+          })
+        }
+      })
+    }, rightAfter)
+
```
Comment (pierremtb) [inline src/components/MlEphantConversation.tsx]: Oh maybe I should move that after onProcess, just a sec

**Review by jacebrowning — APPROVED** [review]
This feels great to me on the Vercel preview!
