### PR TITLE
Fix most Github Actions 'annotations' in PRs

### LINKED ISSUE #383: Fix Github Actions 'annotations' in PRs
image

Results from the build-apps step apparently. It's verbose and annoying on PRs.

### PR DESCRIPTION
**Pull request by pierremtb**
Fixes #383

Those were the same as warnings as in `yarn tauri build`. Here we take care of everything that's _not_ the extensive dependencies for React Hooks, which need case-by-case care.

### CODE REVIEW

**Comment by pierremtb** [comment]
Update desc. I think we should take care of the React Hooks in another PR.

@Irev-Dev this will probably conflict with your xstate PR, which of course has priority!

**Review by Irev-Dev — APPROVED** [review]
Sorry, let's get this in, don't want it lingering longer than it needs to.

Is the cargo tests hard to fix?

**Comment by pierremtb** [comment]
@Irev-Dev oof sorry for all the noise

**Comment by pierremtb** [comment]
@Irev-Dev moving back to draft:

1. with all the new changes there's a ton more to fix
2. need to see what those tests are about, have no context here

**Comment by pierremtb** [comment]
I'll try to get that done quick

File: src-tauri/src/main.rs [hunk 1]
```diff
@@ -87,10 +87,10 @@ async fn login(app: tauri::AppHandle, host: &str) -> Result<String, InvokeError>
 
 fn main() {
     tauri::Builder::default()
-        .setup(|app| {
+        .setup(|_app| {
             #[cfg(debug_assertions)] // only include this code on debug builds
             {
-                let window = app.get_window("main").unwrap();
+                let window = _app.get_window("main").unwrap();
```
[the remark this answers is not in the document]
Comment (pierremtb) [reply src-tauri/src/main.rs:135]: Yeah seems like it's actually meant for that? https://medium.com/codechain/rust-underscore-does-not-bind-fec6a18115a8#:~:text=So%20what%20if%20you%20only,you%20actually%20use%20those%20variables.

I don't remember if I did it because it was suggested by the compiler or nah

File: src/Toolbar.tsx [hunk 2]
```diff
@@ -15,23 +14,6 @@ export const sketchButtonClassnames = {
   icon: 'text-fern-20 h-auto group-hover:text-fern-10 hover:text-fern-10 dark:text-chalkboard-100 dark:group-hover:text-chalkboard-100 dark:hover:text-chalkboard-100 group-disabled:bg-chalkboard-60 hover:group-disabled:text-inherit',
 }
 
-const sketchFnLabels: Record<ToolTip | 'sketch_line' | 'move', string> = {
```
Comment (pierremtb) [inline src/Toolbar.tsx:18]: @Irev-Dev @franknoirot was this forgotten? Or to be used later?

File: src/components/Stream.tsx [hunk 3]
```diff
@@ -267,11 +267,11 @@ export const Stream = ({ className = '' }) => {
       }
       engineCommandManager.sendSceneCommand(command).then(async () => {
         if (!context.sketchPathToNode) return
-        const varDec = getNodeFromPath<VariableDeclarator>(
+        getNodeFromPath<VariableDeclarator>(
```
Comment (pierremtb) [inline src/components/Stream.tsx:270]: Also curious about those. To get the linter happy I removed the var declaration, but do we actually need `getNodeFromPath` executed for something?

Comment (pierremtb) [reply src/components/Stream.tsx:270]: @Irev-Dev

**Comment by pierremtb** [comment]
@Irev-Dev sorry, finally getting to this. The cargo test seems to have solved itself, maybe the rebase on main?

Still keeping the useEffect/useMemo dependencies on the side for another PR as these require more testing

**Comment by pierremtb** [comment]
@Irev-Dev can I get your approval again when you have a chance? There's a few things I'm not sure about but yeah I'd like to have this closed

File: src/Toolbar.tsx (hunk 2 above)
Comment (Irev-Dev) [reply src/Toolbar.tsx:18]: Probably should have been cleaned up in the xstate migration.

File: src/App.tsx [hunk 4]
```diff
@@ -285,7 +286,17 @@ export function App() {
...
+    height,
+    quadHeight,
+    quadWidth,
+    setEngineCommandManager,
+    setIsStreamReady,
+    setMediaStream,
+    setStreamDimensions,
+    token,
+    width,
+  ])
```
[the remark this answers is not in the document]
Comment (pierremtb) [reply src/App.tsx]: Won't take care of those in this PR

File: src/Toolbar.tsx (hunk 2 above)
Comment (pierremtb) [reply src/Toolbar.tsx:18]: Cool, removing is the way to go then

**Comment by pierremtb** [comment]
@Irev-Dev thanks! Finally merging this haha
