### PR TITLE
Fix zookeeper history loss on reconnect and refresh

### LINKED ISSUE #9243: Lost conversation while returning to or refreshing an existing project
Reported by @nicboone8 on Slack at https://kittycadworkspace.slack.com/archives/C06L2RHP9SL/p1765231996553659

### PR DESCRIPTION
**Pull request by lee-at-zoo-corp**
Closes #9243 and #9203 (properly this time)

### CODE REVIEW

File: src/machines/mlEphantManagerMachine2.ts [hunk 1]
```diff
@@ -227,6 +227,15 @@ export const mlEphantManagerMachine2 = setup({
...
     cacheSetup: assign({
+      conversationId: ({ event }) => {
+        assertEvent(event, MlEphantManagerTransitions2.CacheSetupAndConnect)
+
+        if (event.conversationId) {
+          return event.conversationId
+        }
+
+        return undefined
+      },
```
Comment (pierremtb) [inline src/machines/mlEphantManagerMachine2.ts:238]: Yeah makes sense! I actually wanted to go for something like that at first but never gave it a proper shot.
