### PR TITLE
Fix trackball camera by weaving through EngineStream

### LINKED ISSUE #6472: Changing Camera Orbit Between `trackball` & `spherical` doesn't change orbit
### Description
Changing between trackball and spherical camera orbit doesn't change the camera orbit. I tried this on another KCL file and it also didn't change.

### Version
v0.55.0

### Recording
https://github.com/user-attachments/assets/e09bbfe1-f520-4ba1-8dfe-4652a4b1ba7a

### KCL
```js
// Fan Housing
// The plastic housing that contains the fan and the motor

// Set units
@settings(defaultLengthUnit = mm)

// Define parameters
fanSize = 120
fanHeight = 25
mountingHoleSize = 4.5

// Calculated Parameters
mountingHoleSpacing = fanSize - mountingHoleSize * 2

// Model the housing which holds the motor, the fan, and the mounting provisions
// Bottom mounting face
bottomFaceSketch = startSketchOn(XY)
  |> startProfileAt([-fanSize / 2, -fanSize / 2], %)
  |> angledLine(angle = 0, length = fanSize, tag = $rectangleSegmentA001)
  |> angledLine(angle = segAng(rectangleSegmentA001) + 90, length = fanSize, tag = $rectangleSegmentB001)
  |> angledLine(angle = segAng(rectangleSegmentA001), length = -segLen(rectangleSegmentA001), tag = $rectangleSegmentC001)
  |> line(endAbsolute = [profileStartX(%), profileStartY(%)], tag = $rectangleSegmentD001)
  |> close()
  |> hole(circle(center = [0, 0], radius = 4), %)
  |> hole(circle(
       center = [
         mountingHoleSpacing / 2,
         mountingHoleSpacing / 2
       ],
       radius = mountingHoleSize / 2,
     ), %)
  |> hole(circle(
       center = [
         -mountingHoleSpacing / 2,
         mountingHoleSpacing / 2
       ],
       radius = mountingHoleSize / 2,
     ), %)
  |> hole(circle(
       center = [
         mountingHoleSpacing / 2,
         -mountingHoleSpacing / 2
       ],
       radius = mountingHoleSize / 2,
     ), %)
  |> hole(circle(
       center = [
         -mountingHoleSpacing / 2,
         -mountingHoleSpacing / 2
       ],
       radius = mountingHoleSize / 2,
     ), %)
  |> extrude(length = 4)

// Add large openings to the bottom face to allow airflow through the fan
airflowPattern = startSketchOn(bottomFaceSketch, face = END)
  |> startProfileAt([fanSize * 7 / 25, -fanSize * 9 / 25], %)
  |> angledLine(angle = 140, length = fanSize * 12 / 25, tag = $seg01)
  |> tangentialArc(radius = fanSize * 1 / 50, angle = 90)
  |> angledLine(angle = -130, length = fanSize * 8 / 25)
  |> tangentialArc(radius = fanSize * 1 / 50, angle = 90)
  |> angledLine(angle = segAng(seg01) + 180, length = fanSize * 2 / 25)
  |> tangentialArc(radius = fanSize * 8 / 25, angle = 40)
  |> xLine(length = fanSize * 3 / 25)
  |> tangentialArc(endAbsolute = [profileStartX(%), profileStartY(%)])
  |> close()
  |> patternCircular2d(
       instances = 4,
       center = [0, 0],
       arcDegrees = 360,
       rotateDuplicates = true,
     )
  |> extrude(length = -4)

// Create the middle segment of the fan housing body
housingMiddleLength = fanSize / 3
housingMiddleRadius = fanSize / 3 - 1

bodyMiddle = startSketchOn(bottomFaceSketch, face = END)
  |> startProfileAt([
       housingMiddleLength / 2,
       -housingMiddleLength / 2 - housingMiddleRadius
     ], %)
  |> tangentialArc(radius = housingMiddleRadius, angle = 90)
  |> yLine(length = housingMiddleLength)
  |> tangentialArc(radius = housingMiddleRadius, angle = 90)
  |> xLine(length = -housingMiddleLength)
  |> tangentialArc(radius = housingMiddleRadius, angle = 90)
  |> yLine(length = -housingMiddleLength)
  |> tangentialArc(radius = housingMiddleRadius, angle = 90)
  |> line(endAbsolute = [profileStartX(%), profileStartY(%)])
  |> extrude(length = fanHeight - 4 - 4)

// Cut a hole in the body to accommodate the fan
bodyFanHole = startSketchOn(bodyMiddle, face = END)
  |> circle(center = [0, 0], radius = fanSize * 23 / 50)
  |> extrude(length = -(fanHeight - 4 - 4))

// Top mounting face. Cut a hole in the face to accommodate the fan
topFaceSketch = startSketchOn(bodyMiddle, face = END)
topHoles = startProfileAt([-fanSize / 2, -fanSize / 2], topFaceSketch)
  |> angledLine(angle = 0, length = fanSize, tag = $rectangleSegmentA002)
  |> angledLine(angle = segAng(rectangleSegmentA002) + 90, length = fanSize, tag = $rectangleSegmentB002)
  |> angledLine(angle = segAng(rectangleSegmentA002), length = -segLen(rectangleSegmentA002), tag = $rectangleSegmentC002)
  |> line(endAbsolute = [profileStartX(%), profileStartY(%)], tag = $rectangleSegmentD002)
  |> close()
  |> hole(circle(center = [0, 0], radius = fanSize * 23 / 50), %)
  |> hole(circle(
       center = [
         mountingHoleSpacing / 2,
         mountingHoleSpacing / 2
       ],
       radius = mountingHoleSize / 2,
     ), %)
  |> hole(circle(
       center = [
         -mountingHoleSpacing / 2,
         mountingHoleSpacing / 2
       ],
       radius = mountingHoleSize / 2,
     ), %)
  |> hole(circle(
       center = [
         mountingHoleSpacing / 2,
         -mountingHoleSpacing / 2
       ],
       radius = mountingHoleSize / 2,
     ), %)
  |> hole(circle(
       center = [
         -mountingHoleSpacing / 2,
         -mountingHoleSpacing / 2
       ],
       radius = mountingHoleSize / 2,
     ), %)
  |> extrude(length = 4)

// Create a housing for the electric motor to sit
motorHousing = startSketchOn(bottomFaceSketch, face = END)
  |> circle(center = [0, 0], radius = 11.2)
  |> extrude(length = 16)

startSketchOn(motorHousing, face = END)
  |> circle(center = [0, 0], radius = 10)
  |> extrude(length = -16)
  |> appearance(color = "#a55e2c")
  |> fillet(
       radius = abs(fanSize - mountingHoleSpacing) / 2,
       tags = [
         getNextAdjacentEdge(rectangleSegmentA001),
         getNextAdjacentEdge(rectangleSegmentB001),
         getNextAdjacentEdge(rectangleSegmentC001),
         getNextAdjacentEdge(rectangleSegmentD001),
         getNextAdjacentEdge(rectangleSegmentA002),
         getNextAdjacentEdge(rectangleSegmentB002),
         getNextAdjacentEdge(rectangleSegmentC002),
         getNextAdjacentEdge(rectangleSegmentD002)
       ],
     )

```

### PR DESCRIPTION
**Pull request by franknoirot**
Fixes #6472. Just a missing setting moved in #5312, which wasn't caught because testing that the orbit maneuver is actually performing a "trackball-like" movement is nonexistent. I don't know how to test that reliably, but typing this object provides the red squiggles to reveal the missing property.

### CODE REVIEW

**Review by Irev-Dev — APPROVED** [review]

**Comment by Irev-Dev** [comment]
I think `Can move camera reliably` test could be updated, or another added for track ball, since it basically just drags the mouse and expects the camera to have ended up in a specific place, it would be a different place for trackball, so would be an indicator if it suddenly stopped working.

File: src/components/EngineStream.tsx [hunk 1]
```diff
@@ -37,6 +37,7 @@ import {
 } from '@src/lib/utils'
 import { DEFAULT_DEFAULT_LENGTH_UNIT } from '@src/lib/constants'
 import { createThumbnailPNGOnDesktop } from '@src/lib/screenshot'
+import { SettingsViaQueryString } from '@src/lib/settings/settingsTypes'
```
Comment (Irev-Dev) [inline src/components/EngineStream.tsx:40]:
```suggestion
import type { SettingsViaQueryString } from '@src/lib/settings/settingsTypes'
```

**Comment by franknoirot** [comment]
> I think `Can move camera reliably` test could be updated, or another added for track ball, since it basically just drags the mouse and expects the camera to have ended up in a specific place, it would be a different place for trackball, so would be an indicator if it suddenly stopped working.

I like it! https://github.com/KittyCAD/modeling-app/issues/6762
