### PR TITLE
Another attempt at fixing the macOS updater flakiness

### LINKED ISSUE #10009: On MacOS, accepting updater modal can restart without updating, present updater again
While testing the `v1.1.11` release, I followed the release testing template to select `Check for updates` in the native Help menu, which brings up the updater modal. Accepting update and restart did restart the app and bring me to the home page, but with the `v1.1.11` version in the corner, not `v1.1.10` (the updater test while releasing updates backwards).

The updater modal was present after this restart, and I was able to accept it and restart with the update working properly the second time.

### PR DESCRIPTION
**Pull request by pierremtb**
Closes #10009 hopefully for good this time!

Asked Codex and this is what it came up with. Then I cleaned up a few things.

> Implemented based on the suggested sequence from the referenced comment: https://github.com/electron-userland/electron-builder/issues/8997#issuecomment-2846114257
> 
> Changes made in [`src/main.ts:13`](/Users/pierremtb/Documents/zoo/modeling-app-2/src/main.ts:13), [`src/main.ts:66`](/Users/pierremtb/Documents/zoo/modeling-app-2/src/main.ts:66), [`src/main.ts:328`](/Users/pierremtb/Documents/zoo/modeling-app-2/src/main.ts:328), [`src/main.ts:633`](/Users/pierremtb/Documents/zoo/modeling-app-2/src/main.ts:633), [`src/main.ts:675`](/Users/pierremtb/Documents/zoo/modeling-app-2/src/main.ts:675):
> - Added a macOS pre-install path before `quitAndInstall()`.
> - Captures/removes `app` `before-quit` listeners, removes window `close` listeners, then hooks `native autoUpdater` `before-quit-for-update`.
> - In `before-quit-for-update`, re-runs captured quit listeners and explicitly calls `app.exit(0)`.
> - Added an `isInstallingUpdate` guard to avoid duplicate restart attempts and to prevent `window-all-closed` from racing with updater-driven shutdown.

We're also getting rid of `src/updater.ts` as we no longer need that workaround and can directly import now.

Test builds are at https://github.com/KittyCAD/modeling-app/actions/runs/23248843214:
1. Download
2. Install and expect and update
3. Click Restart now
4. See the app close and reopen after a few secs on the last prod builds
5. Go back to Step 2 once or twice

### CODE REVIEW

File: src/menu/helpRole.ts [hunk 1]
```diff
@@ -5,7 +5,7 @@ import { reportRejection } from '@src/lib/trap'
 import { withSiteBaseURL } from '@src/lib/withBaseURL'
 import { typeSafeWebContentsSend } from '@src/menu/channels'
 import type { ZooMenuItemConstructorOptions } from '@src/menu/roles'
-import { getAutoUpdater } from '@src/updater'
+import { autoUpdater as appUpdater } from 'electron-updater'
```
Comment (pierremtb) [inline src/menu/helpRole.ts:8]: I hope this makes things simpler. AppUpdater is the electron-updater type, which isn't the same as the generic autoUpdater class from electron

File: src/main.ts [hunk 2]
```diff
@@ -610,25 +616,70 @@ app.on('ready', () => {
...
+            'Failed to run before-quit listener during update install',
+            error
+          )
+        }
+      }
+
+      // Force app to exit
+      app.exit()
+    })
+  }
```
Comment (pierremtb) [inline src/main.ts:661]: This is the part that's a little more fancy pants

File: src/updater.ts
Comment (pierremtb) [inline src/updater.ts:1]: And yess we can finally get rid of this!
