### PR TITLE
Rejig state diagram for equipping tools

### LINKED ISSUE #2879: Cannot switch back to Line tool after selecting Rectangle tool
🐛

Steps to reproduce:
1. Login
2. Click "Start Sketch"
3. Select a plane to sketch on
4. Select the "Rectangle" tool
5. Click the "Line" tool or use its shortcut button: "L"
Expected: To switch back to the "Line" tool when selected
Actual: Unable to select the "Line" tool while the "Rectangle" tool is selected. 

Additional Context: The "Rectangle" tool can still be deselected to select the "Line" tool correctly

Timestamp: 0:11
Video: 
https://www.loom.com/share/819d971f0a4249f994ff3fce31e109d3?sid=bde216b2-0e92-4ee3-adc7-3c7acdf5fddd (https://www.loom.com/share/819d971f0a4249f994ff3fce31e109d3?sid=bde216b2-0e92-4ee3-adc7-3c7acdf5fddd)

Bug report:
https://app.qawolf.com/zoo/bug-reports/16dc15d7-f224-4f7a-b383-5900258ecaa1

Affected workflows:

If you are aware of this bug you can set the priority to low which will prevent it from causing a run failure.

### PR DESCRIPTION
**Pull request by Irev-Dev**
we got ourselves into an ugly situation where we needed an event from each tool to every other tool.
Used #2879 as motivation for this refactor.

Resolves #2879 

image

### CODE REVIEW

File: src/lib/commandBarConfigs/modelingCommandConfig.ts [hunk 1]
```diff
@@ -37,21 +37,22 @@ export const modelingMachineConfig: CommandSetConfig<
...
+  // 'Equip tangential arc to': {
+  //   description: 'Start drawing an arc tangent to the current segment.',
+  //   icon: 'arc',
+  //   displayName: 'Tangential Arc',
+  // },
+  // 'Equip rectangle tool': {
+  //   description: 'Start drawing a rectangle.',
+  //   icon: 'rectangle',
+  //   displayName: 'Rectangle',
+  // },
```
Comment (Irev-Dev) [inline src/lib/commandBarConfigs/modelingCommandConfig.ts:55]: see https://github.com/KittyCAD/modeling-app/issues/2924
