### PR TITLE
Fix binary STL imports, treat all non-KCL as blobs

### LINKED ISSUE #11107: ZDS mangling binary files in File > Add File To Project
Root cause is [in this comment down below](https://github.com/KittyCAD/modeling-app/issues/11107#issuecomment-4261586029).

Original post:

@r-barton @greg-kcio and a few others encountered an interesting engine error over the week inside ZDS:

```json
{
    "success": false,
    "request_id": "b91cac65-8f42-5c03-bb4d-9f472cae7441",
    "errors": [
      {
        "error_code": "internal_engine",
        "message": "Import failed: internal error: failed to fill whole buffer"
      }
    ]
  }
```

Image

Here is a video @greg-kcio did showing an extremely easy repro:

https://github.com/user-attachments/assets/be2a9a0b-4df2-42c7-92e5-dddc63f50f6e

I have already diagnosed engine paired with a local `api` instance, up to pre-SSI (2 weeks ago). Greg's video clearly shows this is ZDS, as the files become modified without even talking to services.

Full thread here: https://kittycadworkspace.slack.com/archives/C06L2RHP9SL/p1776192287104229

### PR DESCRIPTION
**Pull request by lee-at-zoo-corp**
Resolves https://github.com/KittyCAD/modeling-app/issues/11107
Somewhat higher priority since we showed this to a potential customer and it was broken for them.

### CODE REVIEW

File: src/lib/commandBarConfigs/applicationCommandConfig.ts [hunk 1]
```diff
@@ -186,24 +187,59 @@ export function createApplicationCommands({
...
+                })
+                .catch(() => toast.error(error))
+            }
           })
           fsZds
             .readFile(selectedFilePath)
             .then((content) => {
               const blob = new Blob([new Uint8Array(content)])
-              fr.readAsText(blob)
+              // Read all KCL as text, but anything else is a blob.
```
Comment (adamchalmers) [inline src/lib/commandBarConfigs/applicationCommandConfig.ts:237]: Just checking, why is this necessary? Why not just copy the text byte-by-byte? Is it because we need to make it UTF-16 for editing?

STEP files and OBJ files are also text, but we don't let the user open them in the editor so it's probably fine.

**Review by adamchalmers — APPROVED** [review]

File: src/lib/commandBarConfigs/applicationCommandConfig.ts (hunk 1 above)
Comment (lee-at-zoo-corp) [reply src/lib/commandBarConfigs/applicationCommandConfig.ts:237]: That's why _I_ did it that way, yea, for that concern. It is likely byte-by-byte is ok too!

Comment (lee-at-zoo-corp) [reply src/lib/commandBarConfigs/applicationCommandConfig.ts:237]: I could have checked you're right that it "just works" but it has "just worked" for KCL this way for 1+ years so I didn't want to try
