### PR TITLE
Fix whole module import deletion in feature tree

### LINKED ISSUE #6447: Fix whole module import deletion in feature tree
Image

### PR DESCRIPTION
**Pull request by pierremtb**
Fixes #6447

### CODE REVIEW

File: src/lang/modifyAst.ts [hunk 1]
```diff
@@ -1341,6 +1342,58 @@ export async function deleteFromSelection(
     'VariableDeclarator'
   )
   if (err(varDec)) return varDec
+
+  // Module import and expression case, need to find and delete both
+  if (
+    varDec.node.type !== 'VariableDeclarator' &&
+    varDec.node.type === 'Name'
```
Comment (andrewvarga) [inline src/lang/modifyAst.ts:1349]: This is an interesting condition, it could be just `if (varDec.node.type === 'Name')` ?

Comment (pierremtb) [reply src/lang/modifyAst.ts:1349]: Oh I forgot about this one. This was to make playwright happy, the issue is the call for varDec isn't looking for an ExpressionStatement at all I believe

Comment (pierremtb) [reply src/lang/modifyAst.ts]: I think I made it better

Comment (andrewvarga) [reply src/lang/modifyAst.ts]: yeah, great! Sorry I didn't have all the context, just saw that it could be simplified.

Comment (pierremtb) [reply src/lang/modifyAst.ts]: updated again, keeping it more contained

**Review by andrewvarga — APPROVED** [review]
Looks compact now! I don't have all the context here yet but from what I understand it looks ok.

**Comment by pierremtb** [comment]
Thanks @andrewvarga !
