### PR TITLE
Trim support for circle

### LINKED ISSUE #10732: Trim does not work with circle
There a test suite in rust dedicated to testing the time tool, the cases listed below should be added, expecting them to fail, and then the implementation should be fix to get them to pass. In some ways we might be able to re use the arc logic we already have, since a circle could be view as an arc that completes a full 360, however it is different in a couple of significant ways.
For 1 when a circle is trimmed, it will always need to be converted to an arc in the process, Also a case like case 2 shows something where for other segments this would result in it being split, but this isn't the case for circles since it's just it's endpoints that need to be tweak.

https://github.com/KittyCAD/modeling-app/issues/10741 should be done first, particularly for case 1.3

## case 1.1 "trims a circle into an arc when it's cut in half by a line, and trimed on the side with OUT the start point"

Image

```
@settings(experimentalFeatures = allow)

sketch001 = sketch(on = YZ) {
  circle1 = circle(start = [var -2.67mm, var 1.8mm], center = [var -1.53mm, var 0.78mm])
  line1 = line(start = [var -0.56mm, var 2.8mm], end = [var -3.58mm, var -0.78mm])
}
```

With a trim line that goes through 
```
point(at = [var 0.21mm, var 2.24mm])
point(at = [var -1.23mm, var 1.12mm])
```

should result in the final kcl that looks like
```
@settings(experimentalFeatures = allow)

sketch001 = sketch(on = YZ) {
  line1 = line(start = [var -0.56mm, var 2.8mm], end = [var -3.58mm, var -0.78mm])
  arc1 = arc(start = [var -1.05mm, var 2.23mm], end = [var -2.87mm, var 0.06mm], center = [var -1.53mm, var 0.78mm])
  coincident([arc1.end, line1])
  coincident([arc1.start, line1])
}
```

Image

## case 1.2 "trims a circle into an arc when it's cut in half by a line, and trimed on the side with the start point"

Image

With the same input, but a trim line that goes through the following
```
  point(at = [var -2mm, var 2.86mm])
  point(at = [var -2.53mm, var 1.1mm])
```
Should result in the following kcl code
```
@settings(experimentalFeatures = allow)

sketch001 = sketch(on = YZ) {
  line1 = line(start = [var -0.56mm, var 2.8mm], end = [var -3.58mm, var -0.78mm])
  arc1 = arc(start = [var -2.87mm, var 0.04mm], end = [var -1.03mm, var 2.23mm], center = [var -1.53mm, var 0.78mm])
  coincident([arc1.end, line1])
  coincident([arc1.start, line1])
}
```

Image

## case 1.3 "triming a line that needs to be trimmed up to and mode coincident with the circle"

Image

with the same input again, but a trime line that goes thorugh the following:
```
  point(at = [var -1.24mm, var 2.78mm])
  point(at = [var -0.5mm, var 2.3mm])
```
should result in the following kcl
```
@settings(experimentalFeatures = allow)

sketch001 = sketch(on = YZ) {
  circle1 = circle(start = [var -2.67mm, var 1.8mm], center = [var -1.53mm, var 0.78mm])
  line1 = line(start = [var -1.04mm, var 2.22mm], end = [var -3.58mm, var -0.78mm])
  coincident([line1.start, circle1])
}

```

Image

## case 1.4 "triming a line and circle such that the circle becomes an arc with the end points coincident"

Image

With the same input again, but a trime line that goes through the following:
```
  point(at = [var -1.14mm, var 2.96mm])
  point(at = [var -0.51mm, var 2.22mm])
  point(at = [var -0.4mm, var 0.57mm])
```
 Should generate the following kcl

```
@settings(experimentalFeatures = allow)

sketch001 = sketch(on = YZ) {
  line1 = line(start = [var -1.03mm, var 2.22mm], end = [var -3.58mm, var -0.78mm])
  arc1 = arc(start = [var -1.03mm, var 2.22mm], end = [var -2.88mm, var 0.08mm], center = [var -1.54mm, var 0.79mm])
  coincident([line1.start, arc1.start])
  coincident([arc1.end, line1])
}

```

Image

## case 2 "triming a circle between two segments, should not split the cirle, but instead convert to a arc, with it's start and end points meeting the two segments."

Image

For the following kcl
```
@settings(experimentalFeatures = allow)

sketch001 = sketch(on = YZ) {
  circle1 = circle(start = [var -2.67mm, var 1.8mm], center = [var -1.53mm, var 0.78mm])
  line1 = line(start = [var -0.75mm, var 2.93mm], end = [var -2.97mm, var -1.17mm])
  line2 = line(start = [var -0.1mm, var 2.46mm], end = [var -0.67mm, var 0.97mm])
}

```

With a trim line that goes through
```
  point(at = [var -0.44mm, var 2.72mm])
  point(at = [var -0.99mm, var 1.38mm])
```

The resulting kcl should be:
```
@settings(experimentalFeatures = allow)

sketch001 = sketch(on = YZ) {
  line1 = line(start = [var -0.75mm, var 2.93mm], end = [var -2.97mm, var -1.17mm])
  line2 = line(start = [var -0.1mm, var 2.46mm], end = [var -0.67mm, var 0.97mm])
  arc1 = arc(start = [var -1.13mm, var 2.27mm], end = [var -0.35mm, var 1.77mm], center = [var -1.53mm, var 0.78mm])
  coincident([arc1.end, line2])
  coincident([line1, arc1.start])
}
```

Image

### PR DESCRIPTION
**Pull request by Irev-Dev**
Resolves #10732 

https://github.com/user-attachments/assets/e2f5de69-9205-42fb-8aa3-4982e20e3745

Stacked trim refactor PR
https://github.com/KittyCAD/modeling-app/pull/10919

### CODE REVIEW

File: rust/kcl-lib/src/frontend/trim.rs [hunk 1]
```diff
@@ -862,6 +1118,26 @@ pub fn get_next_trim_spawn(
                     };
                 }
             }
+
+            // Handle Circle segments
+            if let Segment::Circle(_circle) = segment {
```
Comment (Irev-Dev) [inline rust/kcl-lib/src/frontend/trim.rs:1150]: handling the circle case in `get_next_trim_spawn`

File: rust/kcl-lib/src/frontend/trim.rs [hunk 2]
```diff
@@ -978,9 +1254,27 @@ pub fn get_trim_spawn_terminations(
                 })?;
             (start, end, Some(center))
         }
+        Segment::Circle(_) => {
```
Comment (Irev-Dev) [inline rust/kcl-lib/src/frontend/trim.rs:1284]: Add circle handling for `get_trim_spawn_terminations`

File: rust/kcl-lib/src/frontend/trim.rs [hunk 3]
```diff
@@ -2779,6 +3454,100 @@ pub(crate) fn trim_strategy(
...
+            )
+        };
+
+        return Ok(vec![TrimOperation::ReplaceCircleWithArc {
+            circle_id: trim_spawn_id,
+            arc_start_coords,
+            arc_end_coords,
+            arc_start_termination,
+            arc_end_termination,
+        }]);
```
Comment (Irev-Dev) [inline rust/kcl-lib/src/frontend/trim.rs:3574]: A trim line going through a circle only has two outcomes, it either deletes the circle entirely (because something is intersecting it), or the circle is converted to an arc.

Circles are never split because they form a ring, cut somewhere in the ring always loops around, in cases where a trim line going through both sides of a circle and it sure looks like it's been split, the serial nature of this algorithm means it's actually being converted to an arc on teh first intersection with the trim line, and then later it's the arc that's getting split.

Comment (jtran) [reply rust/kcl-lib/src/frontend/trim.rs:3574]: I'll add this as a comment in the code.

**Comment by jtran** [comment]
I reverted my small tweaks to prevent merge conflicts in the refactor.
