### PR TITLE
KCL: Fix cryptic error in type mismatch

### LINKED ISSUE #5616: [CRYPTIC]: Expected a kcl_lib::execution::geometry::SolidSet but found Sketch
### Paste minimal KCL source that produces a cryptic error

```javascript
// Robot Rotating Base


// Set Units
@settings(defaultLengthUnit = in)


import axisJ1, baseHeight, plane002 from "globals.kcl"

// Create Rotating Base
sketch005 = startSketchOn('XY')
  |> circle({ center = [0, 0], radius = 3.9 }, %, $referenceEdge1)
extrude005 = extrude(sketch005, length = 1.5 - 0.1)
  |> fillet(
       radius = 0.1,
       tags = [getOppositeEdge(referenceEdge1)]
  )
  |> appearance(color = "#b86c2e", metalness = 90, roughness = 90)

sketch006 = startSketchOn(plane002)
  |> startProfileAt([3.5, 1.4], %)
  |> angledLine({ angle = 60, length = 1.75 }, %)
  |> arc({
       angleStart = -30,
       angleEnd = -30 + 180,
       radius = 3
     }, %)
  |> angledLineToY({ angle = 60, to = 1.4 }, %)
  |> line(endAbsolute = [profileStartX(%), profileStartY(%)])
  |> close()

extrude006 = extrude(sketch006, length = 1)

sketch007 = startSketchOn(extrude006, 'END')
  |> circle({
       center = [
         1.75 * cos(toRadians(axisJ1)) / abs(cos(toRadians(axisJ1))),
         4.5
       ],
       radius = 2.75
     }, %, $referenceEdge2)
extrude007 = extrude(sketch007, length = 1.5)
  |> fillet(
       radius = 0.1,
       tags = [getOppositeEdge(referenceEdge2)]
  )

// Draw Bolt Pattern on Rotating Base
sketch008 = startSketchOn(extrude007, 'END')
  |> circle({
       center = [
         1.75 * cos(toRadians(axisJ1)) / abs(cos(toRadians(axisJ1))),
         3.25
       ],
       radius = 0.2
     }, %)
  |> patternCircular2d(
       center = [
         1.75 * cos(toRadians(axisJ1)) / abs(cos(toRadians(axisJ1))),
         4.5
       ],
       instances = 4,
       arcDegrees = 360,
       rotateDuplicates = true
     )
extrude008 = extrude(sketch008, length = 0.2)

sketch009 = startSketchOn(extrude007, 'END')
  |> circle({
       center = [
         1.75 * cos(toRadians(axisJ1)) / abs(cos(toRadians(axisJ1))),
         4.5
       ],
       radius = 0.5
     }, %, $referenceEdge3)
extrude009 = extrude(sketch009, length = 0.15)
  |> fillet(
       radius = 0.1,
       tags = [getOppositeEdge(referenceEdge3)]
  )
  |> appearance(color = "#b86c2e", metalness = 90, roughness = 90)

sketch010 = startSketchOn(plane002)
  |> circle({ center = [1.75, 4.5], radius = 0.3 }, %)
  |> appearance(color = "#b86c2e", metalness = 90, roughness = 90)

extrude(sketch010, length = -1)
```

### Expected Behavior

I expect an error here, but not the rust error. We should say something else here. The problem is that `appearance` is piped in a sketch (sketch010).

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by adamchalmers**
Previous error message:
"Expected a kcl_lib::execution::geometry::SolidSet but found Sketch"

New error message:
"Expected a SolidSet but found Sketch. You can convert a sketch (2D) into a Solid (3D) by calling a function like `extrude` or `revolve`"

Two improvements:
 - Don't print the fully-qualified Rust name (e.g. kcl_lib::executor::Solid) instead use the last part of that (e.g. just Solid)
 - Allow specific suggestions for combinations of got/want (e.g. "You can convert a sketch (2D) into a Solid (3D) by calling a function like `extrude` or `revolve`")

Closes #5616

### CODE REVIEW

**Comment by jgomez720** [comment]
>Don't print the fully-qualified Rust name (e.g. kcl_lib::executor::Solid)

I definitely like the idea of shortening this, but some of these errors are still going to be confusing, simply because of the vocabulary we use. For example, `kcl_lib::execution::geometry::SolidSet` would just be `SolidSet`, but I have no idea what a `SolidSet` is.

> Allow specific suggestions for combinations of got/want (e.g. "You can convert a sketch (2D) into a Solid (3D) by calling a function like extrude or revolve")

really like this.

File: rust/kcl-lib/src/std/args.rs [hunk 1]
```diff
@@ -182,13 +182,22 @@ impl Args {
             }))?;
 
         T::from_kcl_val(&arg.value).ok_or_else(|| {
+            let expected_type_name = tynm::type_name::<T>();
```
Comment (nrc) [inline rust/kcl-lib/src/std/args.rs:185]: Rather than add a dep, could we just `rfind("::")` and substring? I don't usually mind adding deps, but this seems pretty easy to do ourselves and I hope we can stop using Rust types for anything user-facing in the short to medium term future too

**Review by nrc — APPROVED** [review]
Nice improvement!

File: rust/kcl-lib/src/std/args.rs (hunk 1 above)
Comment (adamchalmers) [reply rust/kcl-lib/src/std/args.rs:185]: Totally open to it, but, it's a very light dependency, its only dependency is nom, and I like that it can parse traits etc straightforwardly.

I'd rather stop exposing Rust types directly and instead use a trait to give Rust types a KCL human-friendly name... hmmm... let me try that.
