### PR TITLE
Fix fully constrained segments color

### LINKED ISSUE #10694: Fix fully constrained segments color
Currently white on light grey 

Image

### PR DESCRIPTION
**Pull request by pierremtb**
Fixes #10694

### CODE REVIEW

File: src/machines/sketchSolve/segmentsUtils.ts [hunk 1]
```diff
@@ -5,9 +5,12 @@ import {
...
   SKETCH_SELECTION_RGB,
 } from '@src/lib/constants'
+import { getResolvedTheme, Themes } from '@src/lib/theme'
 
-// TODO get this from theme or CSS?
-const TEXT_COLOR = 0xffffff
+const CONSTRAINED_COLOR = {
+  [Themes.Dark]: 0x000000,
+  [Themes.Light]: 0xffffff,
+} as const
```
Comment (Irev-Dev) [inline src/machines/sketchSolve/segmentsUtils.ts:16]: Either this should use vars from https://github.com/KittyCAD/modeling-app/pull/10695/changes#r3012536506

Or vise versa

File: src/machines/sketchSolve/segments.test.ts [hunk 2]
```diff
@@ -427,15 +428,18 @@ describe('deriveSegmentFreedom', () => {
 describe('getSegmentColor', () => {
   const UNCONSTRAINED_COLOR = parseInt('#3c73ff'.replace('#', ''), 16) // Brand blue
   const CONFLICT_COLOR = 0xff5e5b // Coral red
-  const TEXT_COLOR = 0xffffff // White
+  const DARK_CONSTRAINED_COLOR = 0x000000 // Black
+  const LIGHT_CONSTRAINED_COLOR = 0xffffff // White
```
Comment (Irev-Dev) [inline src/machines/sketchSolve/segments.test.ts]: Either this should use https://github.com/KittyCAD/modeling-app/pull/10695/changes#r3012534874

Or vise versa

**Comment by pierremtb** [comment]
@Irev-Dev Thanks! Sorry this was a quick codex attempt and I didn't get a chance to self review yet 🙈

File: src/machines/sketchSolve/segmentsUtils.ts (hunk 1 above)
Comment (pierremtb) [reply src/machines/sketchSolve/segmentsUtils.ts:16]: Thanks I made the change! https://github.com/KittyCAD/modeling-app/pull/10695/commits/6c6631cbb996d0b14925033feead07884f8c2106

File: src/machines/sketchSolve/segments.test.ts (hunk 2 above)
Comment (pierremtb) [reply src/machines/sketchSolve/segments.test.ts]: https://github.com/KittyCAD/modeling-app/commit/6c6631cbb996d0b14925033feead07884f8c2106
