### PR TITLE
Fix source range for parameters with non-default visibility

### LINKED ISSUE #8674: Point-and-click edit of parameters doesn't work for exported ones
`export foo = 1` can't get edited, but `foo = 1` can.

The command palette doesn't let the user go to the review page.

Repo steps:

> Open the car wheel sample
> Loads main.kcl
> Open the File Explorer pane
> Click on parameters.kcl
> Loads parameters.kcl
> Open the Feature Tree pane
> Double click on Parameter lugCount
> Click Continue
> Shows "Can't calculate" for a second, and doesn't progress, you're basically stuck there

### PR DESCRIPTION
**Pull request by pierremtb**
Fixes #8674

### CODE REVIEW

File: src/lib/kclCommands.ts
Comment (pierremtb) [inline src/lib/kclCommands.ts]: @jtran @franknoirot Is there a better way to get the pathToNode of a variable declaration in October 2025?

File: src/lib/kclCommands.ts [hunk 1]
```diff
@@ -324,29 +323,12 @@ export function kclCommands(commandProps: KclCommandConfig): Command[] {
...
-                    name,
-                    value: pathToNode,
-                  }
-                })
-                .filter((a) => !!a) || []
-            )
+            return kclManager.execState.operations.flatMap((op) => {
+              if (op.type !== 'VariableDeclaration') return []
+              if (op.value.type !== 'Number') return []
+              const value = pathToNodeFromRustNodePath(op.nodePath).slice(0, -1)
```
Comment (pierremtb) [inline src/lib/kclCommands.ts:329]: That `.slice(0, -1)` is from https://github.com/KittyCAD/modeling-app/blob/ccc5344d302f9ed89ffc14e04bcbc3908f32e2ad/src/lib/operations.ts#L199-L201

I wanted to also get rid of that but that breaks some edit flows, didn't to over-rotate on it but it's still bothering me :/

**Review by jtran — APPROVED** [review]
Nice!
