### PR TITLE
Flush before planeOf when called on chamfer face

### LINKED ISSUE #7832: Offset plane from chamfer face fails
Example KCL:
```kcl
sketch001 = startSketchOn(XY)
profile001 = startProfile(sketch001, at = [0, 0])
  |> yLine(length = 1.14)
  |> line(endAbsolute = [1.33, 0])
  |> line(endAbsolute = [profileStartX(%), profileStartY(%)], tag = $seg01)
  |> close()
extrude001 = extrude(profile001, length = 2, tagEnd = $capEnd001)
  |> chamfer(
       length = 1,
       tags = [
         getCommonEdge(faces = [seg01, capEnd001])
       ],
       tag = $seg02,
     )

// Error: no entity of that type exists
p0 = planeOf(extrude001, face = seg02)
```

I am unable to get this KCL to run correctly in the app, and @adamchalmers sees it succeed sometimes but fail others. We need to figure out if it is due to IDs or something else further down.

### PR DESCRIPTION
**Pull request by pierremtb**
Fixes #7832

### CODE REVIEW

File: rust/kcl-lib/src/std/planes.rs [hunk 1]
```diff
@@ -60,6 +60,11 @@ pub(crate) async fn inner_plane_of(
         });
     }
 
+    // Flush the batch for our fillets/chamfers if there are any.
+    exec_state
+        .flush_batch_for_solids(args.into(), std::slice::from_ref(&solid))
+        .await?;
```
Comment (pierremtb) [inline rust/kcl-lib/src/std/planes.rs:66]: This is the fix. Borrowed it from elsewhere

**Comment by jtran** [comment]
cargo test failed because you need to regen the sim test output now that the `gdt` module merged.
