### PR TITLE
Attempt at fixing two cases of ghost selections

### LINKED ISSUE #8231: Selecting all code and deleting it leaves the selection as "1 face"
Unsure what's up here but I'll attach a video. If you select all the code in the editor the selection always says "1 face" which is reviewable in the lower-right corner, and when you delete all that code that selection does not update to "no selection".

https://github.com/user-attachments/assets/cfbfe072-e820-46d8-8f36-aadde345d356

### PR DESCRIPTION
**Pull request by pierremtb**
Closes #8231

As mentioned in https://github.com/KittyCAD/modeling-app/issues/8231#issuecomment-3587433809:
> 1. After code deletion (which means we have deselected in codemirror), we re-execute properly but don't clear the selections
> 2. After code deletion, clicking in the empty program OR clicking at the end anytime (last new line) of a non-empty program leads to that 1 other ghost selection

One commit for each here.

### CODE REVIEW

File: src/lib/selections.ts [hunk 1]
```diff
@@ -325,6 +325,14 @@ export function processCodeMirrorRanges({
   for (const { id, range } of idBasedSelections) {
     if (!id) {
       const pathToNode = getNodePathFromSourceRange(ast, range)
+      const invalidPathToNode =
+        pathToNode.length === 1 &&
+        pathToNode[0][0] === 'body' &&
+        pathToNode[0][1] === ''
```
Comment (pierremtb) [inline src/lib/selections.ts:331]: I think we should catch those at the Rust level. Maybe this '1 other' bug started appearing when we moved over?

File: src/editor/plugins/lsp/kcl/index.ts [hunk 2]
```diff
@@ -147,8 +147,10 @@ export class KclPlugin implements PluginValue {
     }
 
     if (!this.client.ready) return
+
+    const clearSelections = true // no reason to keep them after a manual edit
     // eslint-disable-next-line @typescript-eslint/no-floating-promises
-    kclManager.executeCode()
+    kclManager.executeCode(clearSelections)
```
Comment (pierremtb) [inline src/editor/plugins/lsp/kcl/index.ts:153]: It's the first time I'm tracking this down, was surprised to see execution triggered from the LSP! Took me a bit to get here. This is probably not the cleanest approach, open to suggestions

Comment (franknoirot) [reply src/editor/plugins/lsp/kcl/index.ts:153]: Right? It's so convoluted. This is what I want us to wrangle with #8880 and #8885. I think I would rather make another method on `KclManager` like `clearSelection`, but this class is changing a lot right now and this is easy to adjust as we go forward.
