### PR TITLE
No tooltip if billing error and fix billing error typing in machine

### LINKED ISSUE #8300: Error after submitting a Text-to-CAD prompt on zoogov.dev
Image

Context: https://kittycadworkspace.slack.com/archives/C07A80B83FS/p1757803669146539

### PR DESCRIPTION
**Pull request by pierremtb**
Fixes #8300

Needs https://github.com/KittyCAD/react-shared/pull/18 and https://github.com/KittyCAD/react-shared/pull/19

### CODE REVIEW

File: src/machines/billingMachine.ts [hunk 1]
```diff
@@ -108,7 +108,9 @@ export const billingMachine = setup({
           {
             target: BillingState.Waiting,
             // Yep, this is hard to follow. XState, why!
-            actions: assign({ error: ({ event }) => event.error as Error }),
+            actions: assign({
```
Comment (lee-at-zoo-corp) [inline src/machines/billingMachine.ts:111]: You should be able to return a BillingError in the event data and not use as here, but I'm going to put the responsibility of this on me saying "it's ok" so we can move this through so Blue doesn't see this UX oddity anymore :)

**Review by lee-at-zoo-corp — APPROVED** [review]

File: src/machines/billingMachine.ts (hunk 1 above)
Comment (pierremtb) [reply src/machines/billingMachine.ts:111]: Added a TODO for now, ty

Comment (pierremtb) [reply src/machines/billingMachine.ts:111]: Will try @franknoirot's suggestion on Slack quick tho

Comment (pierremtb) [reply src/machines/billingMachine.ts:111]: Well not getting it to work now, will stick to the TODO
