### PR TITLE
Fix Shell point-and-click bug with sketch on face

### LINKED ISSUE #7334: [BUG]: Shell codegen for multiple sketch on faces
### Describe the bug

Skipped a face when using point and click to shell an object with multiple appendages

Is the way shell faces are tagged in KCL robust enough?

### Steps to Reproduce

1. create an extruded body
2. sketch a profile on one of the faces of the original body and extrude
3. sketch another profile on another face of the original body and extrude
4. try to shell the solid so that the end face of each new extrusion is removed

```
sketch001 = startSketchOn(XY)
profile001 = startProfile(sketch001, at = [-42.16, -37.03])
  |> angledLine(angle = 0, length = 80.9, tag = $rectangleSegmentA001)
  |> angledLine(angle = segAng(rectangleSegmentA001) + 90, length = 76.34, tag = $seg01)
  |> angledLine(angle = segAng(rectangleSegmentA001), length = -segLen(rectangleSegmentA001), tag = $seg03)
  |> line(endAbsolute = [profileStartX(%), profileStartY(%)], tag = $seg02)
  |> close()
extrude001 = extrude(profile001, length = 200)

sketch002 = startSketchOn(extrude001, face = seg01)
profile002 = circle(sketch002, center = [10.97, 184.86], radius = 7.9)
extrude002 = extrude(profile002, length = 12)

sketch003 = startSketchOn(extrude001, face = rectangleSegmentA001)
profile003 = circle(sketch003, center = [-13.7, 19.04], radius = 8.42)
extrude003 = extrude(profile003, length = 12)

//Point and Click Shell Output
shell001 = shell(extrude003, faces = [END, END], thickness = 1)
```

### Expected Behavior

`shell001 = shell([extrude002, extrude003], faces = [END], thickness = 1)`

### Screenshots and Recordings

Image

### Desktop OS

Windows 11

### Browser

_No response_

### Version

v25.6.02

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by pierremtb**
Fixes #7334

### CODE REVIEW

File: src/lang/modifyAst/faces.ts [hunk 1]
```diff
@@ -71,11 +71,15 @@ export function addShell({
   const mNodeToEdit = structuredClone(nodeToEdit)
 
   // 2. Prepare unlabeled and labeled arguments
+  // Because of START and END untagged caps, we can't rely on last child here
+  // Haven't found a case where it would be needed anyway
+  const lastChildLookup = false
```
Comment (pierremtb) [inline src/lang/modifyAst/faces.ts:76]: This is the fix

File: src/lang/modifyAst/faces.spec.ts [hunk 2]
```diff
@@ -336,7 +360,61 @@ shell001 = shell(extrude001, faces = [seg01, seg02], thickness = 2)`)
...
+      await enginelessExecutor(
+        result.modifiedAst,
+        undefined,
+        undefined,
+        rustContextInThisFile
+      )
+    })
+
+    it('should add a shell on an end face of an extrude later sketched on in another direction', async () => {
+      // Code from https://github.com/KittyCAD/modeling-app/issues/7334#issuecomment-3493494067
```
Comment (pierremtb) [inline src/lang/modifyAst/faces.spec.ts:372]: This is the new test case

File: src/lang/modifyAst/faces.spec.ts [hunk 3]
```diff
@@ -182,7 +182,12 @@ extrude001 = extrude(profile001, length = 10, tagEnd = $capEnd001)
       expect(newCode).toContain(
         `shell001 = shell(extrude001, faces = END, thickness = 1)`
       )
-      await enginelessExecutor(ast, undefined, undefined, rustContextInThisFile)
+      await enginelessExecutor(
+        result.modifiedAst,
+        undefined,
+        undefined,
+        rustContextInThisFile
+      )
```
Comment (pierremtb) [inline src/lang/modifyAst/faces.spec.ts:190]: This is just cleanup throughout the file: those test cases weren't checking the new ast for mock exec errors! Thanks bot

**Review by nicboone8 — APPROVED** [review]

**Review by franknoirot — APPROVED** [review]
Code review looks good, and I manually tested the error case in #7334 and see the corrected behavior. Nice!
