### PR TITLE
Harden KclManager against multiple writers

### LINKED ISSUE #10620: Multiple instances: Code edits sometimes clears the whole file
Reported by an external user on Discord. Slack thread https://kittycadworkspace.slack.com/archives/C07A80B83FS/p1774570599929689

1.1.18, Desktop app, two instances opened.

### LINKED ISSUE #10809: Editing KCL while sketching can cause code to get deleted
### Describe the bug

Flicker, then code pane delete when dimensioning a bunch of circles in sequence. I was able to repro with the code below.

https://github.com/user-attachments/assets/94a42d4b-3e6a-48a6-ad7e-d96ce30a1f31

### Steps to Reproduce

```
// Set units
@settings(defaultLengthUnit = in, kclVersion = 1.0, experimentalFeatures = allow)

// Input bolt pattern dimensions to mount the bracket
mountingBoltDiameter = 1 / 4
mountingBoltPatternX = 7
mountingBoltPatternY = 4

// Input bolt pattern dimensions to mount a component to the bracket
componentBoltDiameter = 3 / 16
componentBoltPatternX = 2
componentBoltPatternY = 3

sketch001 = sketch(on = XY) {
  line1 = line(start = [var -7.55in, var -5.79in], end = [var 7.55in, var -5.79in], construction = true)
  line2 = line(start = [var 7.55in, var -5.79in], end = [var 7.55in, var 5.79in], construction = true)
  line3 = line(start = [var 7.55in, var 5.79in], end = [var -7.55in, var 5.79in], construction = true)
  line4 = line(start = [var -7.55in, var 5.79in], end = [var -7.55in, var -5.79in], construction = true)
  coincident([line1.end, line2.start])
  coincident([line2.end, line3.start])
  coincident([line3.end, line4.start])
  coincident([line4.end, line1.start])
  parallel([line2, line4])
  parallel([line3, line1])
  perpendicular([line1, line2])
  horizontal(line3)
  line5 = line(start = [var -16.76in, var -13.56in], end = [var 16.76in, var -13.56in], construction = true)
  line6 = line(start = [var 16.76in, var -13.56in], end = [var 16.76in, var 13.56in], construction = true)
  line7 = line(start = [var 16.76in, var 13.56in], end = [var -16.76in, var 13.56in], construction = true)
  line8 = line(start = [var -16.76in, var 13.56in], end = [var -16.76in, var -13.56in], construction = true)
  coincident([line5.end, line6.start])
  coincident([line6.end, line7.start])
  coincident([line7.end, line8.start])
  coincident([line8.end, line5.start])
  parallel([line6, line8])
  parallel([line7, line5])
  perpendicular([line5, line6])
  horizontal(line7)
  line9 = line(start = [var -16.76in, var 13.56in], end = [var -0in, var -0in], construction = true)
  coincident([line9.start, line8.start])
  coincident([line9.end, ORIGIN])
  line10 = line(start = [var -0in, var -0in], end = [var 16.76in, var -13.56in], construction = true)
  coincident([line10.start, line9.end])
  coincident([line10.end, line6.start])
  line11 = line(start = [var 7.55in, var 5.79in], end = [var -0in, var -0in], construction = true)
  coincident([line11.start, line3.start])
  coincident([line11.end, line10.start])
  line12 = line(start = [var -0in, var -0in], end = [var -7.55in, var -5.79in], construction = true)
  coincident([line12.start, line11.end])
  coincident([line12.end, line4.end])
  parallel([line9, line10])
  equalLength([line9, line10])
  parallel([line12, line11])
  equalLength([line12, line11])
  distance([line5.start, line5.end]) == 33.52in
  distance([line6.start, line6.end]) == 27.12in
  distance([line1.start, line1.end]) == 15.1in
  distance([line2.start, line2.end]) == 11.58in
  circle1 = circle(start = [var -20.7in, var 15.39in], center = [var -16.76in, var 13.56in])
  coincident([circle1.center, line9.start])
  circle2 = circle(start = [var -19.36in, var -17.22in], center = [var -16.76in, var -13.56in])
  coincident([circle2.center, line8.end])
  circle3 = circle(start = [var 20.08in, var -16.61in], center = [var 16.76in, var -13.56in])
  coincident([circle3.center, line10.end])
  circle4 = circle(start = [var 21.35in, var 10.44in], center = [var 16.76in, var 13.56in])
  coincident([circle4.center, line7.start])
  circle5 = circle(start = [var 10.28in, var 3.88in], center = [var 7.55in, var 5.79in])
  coincident([circle5.center, line11.start])
  circle6 = circle(start = [var -9.18in, var 3.96in], center = [var -7.55in, var 5.79in])
  coincident([circle6.center, line4.start])
  circle7 = circle(start = [var -6.26in, var -8.07in], center = [var -7.55in, var -5.79in])
  coincident([circle7.center, line12.end])
  circle8 = circle(start = [var 7.14in, var -8.3in], center = [var 7.55in, var -5.79in])
  coincident([circle8.center, line2.start])
  radius(circle1) == 4.34in
  radius(circle4) == 5.55in
  radius(circle3) == 4.51in
  radius(circle2) == 4.49in
  radius(circle7) == 2.62in
  radius(circle6) == 2.45in
  radius(circle5) == 3.33in
  radius(circle8) == 2.54in
}

```

### Expected Behavior

.

### Screenshots and Recordings

_No response_

### Desktop OS

win11

### Browser

_No response_

### Version

staging

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by franknoirot**
Codex-assisted refactor of the file writing loop in `KclManager`. Closes #10809 and #10620.

1. Adds monotonic document version tracking so async editor rewrites and disk writes can detect stale work and avoid committing older state over newer edits.
2. Changes disk writes to re-read the on-disk file before saving and skip writes when disk has changed since the last known sync, preventing blind overwrites during multi-instance or competing-write scenarios.
3. Blocks automatic file-watch reloads when the in-memory editor buffer has unsaved local changes, so external updates do not clobber dirty editor state.
4. Adds per-file recovery snapshots for unsynced editor contents and restores them on reopen, making recent unsaved code recoverable after crashes or interrupted sessions. This recovery snapshot persistence is moved off the hot typing path by debouncing snapshot writes instead of synchronously writing recovery state on every document change.
6. Narrows stale-write cancellation so programmatic sketch/system editor rewrites can proceed through internal document churn while still being canceled by newer direct user edits.
7. Stops implicit autosaves from treating programmatic `updateCodeEditor()` transactions like direct typing, reducing false save conflicts during internal editor synchronization.
8. Refactors the debounced `writeToFile()` path to try to make the write loop easier to reason about and maintain.
9. Adds targeted integration coverage in `KclManager.spec.ts` for stale async rewrites, blocked dirty reloads, CAS-style write conflicts, and recovery snapshot restore behavior.

### CODE REVIEW

File: src/lang/KclManager.ts [hunk 1]
```diff
@@ -806,13 +809,32 @@ export class KclManager extends File {
...
+
+        if (this.hasUnsavedLocalChanges()) {
+          console.warn(
+            'External file change detected while local edits are unsaved. Skipping automatic reload to avoid overwriting the editor buffer.'
+          )
+          toast.error(
+            'File changed on disk while this editor has unsaved changes. Reload was skipped to protect your work.'
+          )
+          return
+        }
```
Comment (franknoirot) [inline src/lang/KclManager.ts:837]: This is the heart of the new protection mechanism

File: src/lang/KclManager.ts [hunk 2]
```diff
@@ -1049,7 +1073,20 @@ export class KclManager extends File {
   private syncCodeSignalToDoc = EditorView.updateListener.of((update) => {
     if (update.docChanged) {
       const newCode = update.view.state.doc.toString()
+      this._documentVersion += 1
```
Comment (franknoirot) [inline src/lang/KclManager.ts:1084]: @jtran I was happy to see that one of the solutions presented by Codex was an automatic incrementing document version number here. I think this will be able to be piped through to make the Rust side version-aware as well in future PRs.

File: src/lang/KclManager.ts [hunk 3]
```diff
@@ -2880,28 +2966,74 @@ export class KclManager extends File {
...
-                this.timeoutRewatch = undefined
-              }, 1_000)
-            })
-            .catch((err: unknown) => {
-              // TODO: add tracing per GH issue #254 (https://github.com/KittyCAD/modeling-app/issues/254)
-              console.warn('error saving file', err)
-              toast.error('Error saving file, please check file permissions.')
-              reject(err)
-            })
+          void (async () => {
```
Comment (Irev-Dev) [inline src/lang/KclManager.ts]: This is definitely a little smell, I know the timeout was already hear, but having a `( async () => {})()` within a `setTimeout(...)` is like going from cringe to mega cringe. Might be worth asking Codex for a bit of clean up around this function while we're here?

**Review by Irev-Dev — COMMENTED** [review]
There's one smelly bit of code I'm not real keen on that.

And I have one other question, From what I understand this is just making sure there are not syncing issue between the file on disk and the editor, which by definition is just a single file.

I'm just thinking ahead to when we have buffers for multiple files, this will probably need to be expanded for multiple files, but nothing to do just yet I'm assuming.

Sorry open ended question.

Also little nit, I found the description on this PR a bit hard to follow, it was like a story of you prompting Codex, and multiple of it's responses etc, In reviewing I kinda just want to cut to the chase and be told a summary of the final result etc. I'm sure you were trying to be open about the process, but overall just felt a bit meandering as a PR description

**Comment by Irev-Dev** [comment]
"Harden" makes me think of
image

**Comment by franknoirot** [comment]
> Also little nit, I found the description on this PR a bit hard to follow, it was like a story of you prompting Codex, and multiple of it's responses etc, In reviewing I kinda just want to cut to the chase and be told a summary of the final result etc. I'm sure you were trying to be open about the process, but overall just felt a bit meandering as a PR description

Yeah that's fair, I apologize. This is the loosest grip I've had of understanding a PR of mine, and I was outsourcing the job of clarifying it to the prompts themselves. Won't happen again, and I'll get this cleaned up today.

File: src/lang/KclManager.ts (hunk 3 above)
Comment (franknoirot) [reply src/lang/KclManager.ts]: Yeah absolutely, I think I've gotten it to clean things up in [fa312ef](https://github.com/KittyCAD/modeling-app/pull/10918/commits/fa312ef5e61d2d883734359a14b8d2c2c879be8c)

**Review by Irev-Dev — APPROVED** [review]
