### PR TITLE
Tauri e2e coverage: check filesystem settings, create/open file

### LINKED ISSUE #1190: Create a file and expect stream to fail on Linux

### PR DESCRIPTION
**Pull request by pierremtb**
Fixes #1190

### CODE REVIEW

File: src/routes/Home.tsx [hunk 1]
```diff
@@ -37,13 +37,20 @@ import { homeCommandBarConfig } from 'lib/commandBarConfigs/homeCommandConfig'
 const Home = () => {
   const { commandBarSend } = useCommandsContext()
   const navigate = useNavigate()
-  const { projects: loadedProjects } = useLoaderData() as HomeLoaderData
+  const { projects: loadedProjects, newDefaultDirectory } =
+    useLoaderData() as HomeLoaderData
```
Comment (pierremtb) [inline src/routes/Home.tsx:41]: Workaround outlined by @franknoirot at https://kittycadworkspace.slack.com/archives/C04KFV6NKL0/p1702903770218659

File: e2e/tauri/specs/auth.e2e.ts [hunk 2]
```diff
@@ -49,14 +56,51 @@ describe('KCMA (Tauri, Linux)', () => {
...
+    const nameInput = await $('[data-testid="name-input"]')
+    expect(await nameInput.getValue()).toEqual('project-$nnn')
+
+    const closeButton = await $('[data-testid="close-button"]')
+    await click(closeButton)
+  })
+
+  it('checks that no file exists, creates a new file', async () => {
+    const homeSection = await $('[data-testid="home-section"]')
+    expect(await homeSection.getText()).toContain('No Projects found')
```
Comment (franknoirot) [inline e2e/tauri/specs/auth.e2e.ts:80]: Adding a note in my goals doc to start consolidating microcopy like "No Projects found" so that tests don't break as much as we make improvements to the UI.

**Review by franknoirot — APPROVED** [review]
Looks good to me! In future we might try to avoid using `data-testid`'s, I know @Irev-Dev has expressed interest in trying to test the app as closely to the user's behavior and I'm inclined to agree for a couple reasons. But that's not at all important for this right now, nice job!

**Comment by Irev-Dev** [comment]
> Looks good to me! In future we might try to avoid using `data-testid`'s, I know @Irev-Dev has expressed interest in trying to test the app as closely to the user's behavior and I'm inclined to agree for a couple reasons. But that's not at all important for this right now, nice job!

I know that the tools that @pierremtb has to use make it a bit more difficult to query by things other than attributes like test id so I'm not too worried about it. Maybe we'de be able to make some of our own query utils that gives us back `getByRole`/`getByText` functionality, but not a big priority.

**Review by Irev-Dev — APPROVED** [review]

**Comment by pierremtb** [comment]
@franknoirot @Irev-Dev Alright, thanks a lot for taking the time folks! I believe that's what I'm limited to with wdio https://webdriver.io/docs/selectors/ (provided implementation by tauri-driver). Definitely interested in hearing/reading more about the preference for getByText/Role types.
