### PR TITLE
fix sketch mode scale issue

### LINKED ISSUE #5621: `circle` click and point displaying incorrect units while sketching
### Description
Circle is displaying incorrect units while using click and point. Final render is different from what's displayed in sketch tool.

### Version
v0.46.0

### Recording
https://github.com/user-attachments/assets/f3e203e1-cefe-43dc-a8e7-a413589602ca

### KCL
```js
@settings(defaultLengthUnit = in)
// Flange
// A flange is a flat rim, collar, or rib, typically forged or cast, that is used to strengthen an object, guide it, or attach it to another object. Flanges are known for their use in various applications, including piping, plumbing, and mechanical engineering, among others.


// Set units


// Define constants
mountingHoleDia = .625
baseDia = 4.625
pipeDia = 1.25
thickness = .625
totalThickness = 0.813
topTotalDiameter = 2.313
bottomThickness = 0.06
bottomTotalDiameter = 2.5
mountingHolePlacementDiameter = 3.5
baseThickness = .625
topTotalThickness = totalThickness - (bottomThickness + baseThickness)
holeLocator = baseDia - 8
nHoles = 4

// Add assertion so nHoles are always greater than 1
assertGreaterThan(nHoles, 1, "nHoles must be greater than 1")

// Create the circular pattern for the mounting holes
circles = startSketchOn('XY')
  |> circle({
       center = [mountingHolePlacementDiameter / 2, 0],
       radius = mountingHoleDia / 2
     }, %)
  |> patternCircular2d(
       arcDegrees = 360,
       center = [0, 0],
       instances = nHoles,
       rotateDuplicates = true,
     )

// Create the base of the flange and add the mounting holes
flangeBase = startSketchOn('XY')
  |> circle({
       center = [0, 0],
       radius = baseDia / 2
     }, %)
  |> hole(circles, %)
  // |> hole(circle({
  // center = [0, 0],
  // radius = pipeDia / 2
  // }, %), %)
  |> extrude(length = baseThickness)

topExtrusion = startSketchOn(flangeBase, 'end')
  |> circle({
       center = [0, 0],
       radius = topTotalDiameter / 2
     }, %)
  |> extrude(length = topTotalThickness)

// Plane for top face
topFacePlane = {
  plane = {
    origin = { x = 0, y = 0, z = baseThickness },
    xAxis = { x = 1, y = 0, z = 0 },
    yAxis = { x = 0, y = 1, z = 0 },
    zAxis = { x = 0, y = 0, z = 1 }
  }
}
```

### PR DESCRIPTION
**Pull request by Irev-Dev**
Where the scale get's set for the client side sketch scene needed updating since it's not coming through settings anymore.

Should close #5621 

Follow up to #5808/#3960

I have a feeling this is going to cause hella CI adjustments :( 🤞

### CODE REVIEW

File: src/machines/settingsMachine.ts [hunk 1]
```diff
@@ -174,14 +174,6 @@ export const settingsMachine = setup({
...
   },
   actions: {
-    setClientSideSceneUnits: ({ context, event }) => {
-      const newBaseUnit =
-        event.type === 'set.modeling.defaultUnit'
-          ? (event.data.value as BaseUnit)
-          : context.modeling.defaultUnit.current
-      if (!sceneInfra) return
-      sceneInfra.baseUnit = newBaseUnit
-    },
```
Comment (Irev-Dev) [inline src/machines/settingsMachine.ts:184]: Now redundant, this action has been removed.

**Review by jtran — APPROVED** [review]

**Review by pierremtb — APPROVED** [review]

**Comment by pierremtb** [comment]
Force merged based on the all green status of https://github.com/KittyCAD/modeling-app/pull/6107/commits/a56579fa068993656828365369c49f9c64d694cd before the last merge from main
