### PR TITLE
#6548 Fix autocomplete for offsetPlane

### LINKED ISSUE #6548: Autocomplete `offsetPlane` doesn't give all parameters
### Description
`offsetPlane` does not autocomplete with all necessary parameters

### Recording
https://github.com/user-attachments/assets/f50c2777-3eb1-4825-9d73-93ba1ae602c0

### Verson
v0.56.0

### PR DESCRIPTION
**Pull request by andrewvarga**
Fixes #6548

### CODE REVIEW

File: rust/kcl-lib/src/docs/kcl_doc.rs [hunk 1]
```diff
@@ -788,6 +788,7 @@ impl ArgData {
             Some("Axis2d | Edge") | Some("Axis3d | Edge") => Some((index, format!(r#"{label}${{{index}:X}}"#))),
             Some("Edge") => Some((index, format!(r#"{label}${{{index}:tag_or_edge_fn}}"#))),
             Some("[Edge; 1+]") => Some((index, format!(r#"{label}[${{{index}:tag_or_edge_fn}}]"#))),
+            Some("Plane") => Some((index, format!(r#"{label}${{{}:XZ}}"#, index))),
```
Comment (andrewvarga) [inline rust/kcl-lib/src/docs/kcl_doc.rs:791]: should the default be XZ, or XY? The doc refers to XY in many cases but to me it feels like the most common plane to start a sketch on is the Front plane (XZ)

**Comment by jessfraz** [comment]
add a rust test here: https://github.com/KittyCAD/modeling-app/blob/main/rust/kcl-lib/src/docs/mod.rs#L1172 i dont like relying on playwright for this, your test is great but a rust test we wont disable on a whim

**Comment by jessfraz** [comment]
heres an exmaple of a function: https://github.com/KittyCAD/modeling-app/blob/main/rust/kcl-lib/src/docs/mod.rs#L1150

**Comment by andrewvarga** [comment]
> add a rust test here: https://github.com/KittyCAD/modeling-app/blob/main/rust/kcl-lib/src/docs/mod.rs#L1172 i dont like relying on playwright for this, your test is great but a rust test we wont disable on a whim

Added a rust test, I assume we still want to keep the playwright test but lmk if not.
