### PR TITLE
Fix bug with `undo startSketchOn` removing existing sketch

### LINKED ISSUE #6822: [BUG]: Exit sketch is deleting sketch
### Describe the bug

I'll poke at this more, see if I can replicate it with different KCL. 

Any time I edit then exit the second sketch, the whole sketch gets deleted. Ctrl-z brings it back

I also keep getting kicked out of sketch mode for both sketches

https://github.com/user-attachments/assets/2859424b-b338-483c-a834-d39cd8ed9ede

https://github.com/user-attachments/assets/38befc68-cd08-40da-968c-44d495b6a78a

### Steps to Reproduce

fanHeight = 25

// Model the center of the fan
fanCenter = startSketchOn(XY)
  |> startProfile(at = [-0.0001, fanHeight])
  |> xLine(endAbsolute = -15 + 1.5)
  |> tangentialArc(radius = 1.5, angle = 90)
  |> yLine(endAbsolute = 4.5)
  |> xLine(endAbsolute = -13)
  |> yLine(endAbsolute = profileStartY(%) - 5)
  |> tangentialArc(radius = 1, angle = -90)
  |> xLine(endAbsolute = -1)
  |> yLine(length = 2)
  |> xLine(length = -0.15)
  |> line(endAbsolute = [
       profileStartX(%) - 1,
       profileStartY(%) - 1.4
     ])
  |> xLine(endAbsolute = profileStartX(%))
  |> yLine(endAbsolute = profileStartY(%))
  |> close()
sketch001 = startSketchOn(XY)
  |> startProfile(at = [fanHeight, 0])
  |> yLine(endAbsolute = -15 + 1.5)
  |> tangentialArc(radius = 1.5, angle = -90)
  |> xLine(endAbsolute = 4.5)
  |> yLine(length = 2.38)
  |> xLine(length = 13.02)
  |> tangentialArc(radius = 1, angle = -90)
  |> yLine(length = 3.11)
  |> line(end = [1.31, 0.16])
  |> line(end = [-0.48, 2.05])
  |> line(endAbsolute = [profileStartX(%), profileStartY(%)])
  |> close()

### Expected Behavior

Expected to be able to edit either sketch

### Screenshots and Recordings

_No response_

### Desktop OS

Windows 11

### Browser

_No response_

### Version

v25.5.10

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by franknoirot**
Fixes #6822, I believe. in this case the `variableName` was not being marked as in-use, so I just logged out the AST and made sure this case was covered. @Irev-Dev this is probably worth a check from you.

## Demo

https://github.com/user-attachments/assets/a6025520-7d47-43c1-9495-3b9c7d9204e8

### CODE REVIEW

**Review by Irev-Dev — APPROVED** [review]
I did end up doing my own push

I think what was needed here was to check that the expression was not a pipe. The original changes broke the case when you create a new sketch, don't add any profiles, so we clean up the "startSketchOn" so that it's not lingering.

File: src/components/ModelingMachineProvider.tsx [hunk 1]
```diff
@@ -751,13 +751,22 @@ export const ModelingMachineProvider = ({
...
-                enter: (node) => {
-                  if (node.type === 'Name' && node.name.name === variableName) {
-                    isIdentifierUsed = true
-                  }
-                },
-              })
+              const isInitAPipe =
+                varDec.node.declaration.init.type === 'PipeExpression'
+              if (isInitAPipe) {
+                isIdentifierUsed = true
```
Comment (Irev-Dev) [inline src/components/ModelingMachineProvider.tsx:757]: Name is not the best now that we're check for use in general not only if it's the identifier but 🤷 too late now.
