### PR TITLE
fix ply and stl exports

### LINKED ISSUE #1140: STL and PLY exports broken
see: https://github.com/KittyCAD/modeling-app/pull/1139/files#r1408555138
uncomment that part ☝️ of the export test when this is resolved

ofc, this may not be no a modelling app issue

### PR DESCRIPTION
**Pull request by Irev-Dev**
Uses latest kittycad.ts to fix app export issues.
Resolves #1140

### CODE REVIEW

File: src/components/ExportButton.tsx [hunk 1]
```diff
@@ -177,13 +180,13 @@ export const ExportButton = ({ children, className }: ExportButtonProps) => {
...
                     <>
                       <option value="ascii">ascii</option>
                       <option value="binary">binary</option>
                     </>
                   )}
-                  {type === 'stl' && (
+                  {type === 'ply' && (
                     <>
                       <option value="ascii">ascii</option>
                       <option value="binary_little_endian">
```
Comment (Irev-Dev) [inline src/components/ExportButton.tsx:192]: This looked like an existing bug where we were giving wrong options for stl and ply

File: src/components/ExportButton.tsx [hunk 2]
```diff
@@ -86,6 +86,9 @@ export const ExportButton = ({ children, className }: ExportButtonProps) => {
         // Set the storage type.
         values.storage = storage
       }
+      if (values.type === 'ply' || values.type === 'stl') {
+        values.selection = { type: 'default_scene' }
```
Comment (Irev-Dev) [inline src/components/ExportButton.tsx:90]: @jessfraz @alteous is hardcoding this to 'default_scene' okay for ply and stl?

Comment (jessfraz) [reply src/components/ExportButton.tsx:94]: Yes that's what I'd do
