### PR TITLE
#10847 Sketch profile alignment fix

### LINKED ISSUE #10847: The sketch profile appears mirrored when clicking "Edit Sketch"
### Describe the bug

The sketch is applied to the Left (-YZ) plane. When I click "Edit sketch", the camera rotates to view the Right plane, but the sketch profile appears mirrored as if looking at the Left plane.

### Steps to Reproduce

With sketch_solve enabled and with the code below in main.kcl, click `sketch001` in the feature tree, then click "Edit Sketch".

```
@settings(experimentalFeatures = allow)

sketch001 = sketch(on = -YZ) {
  line1 = line(start = [var 0mm, var 0mm], end = [var -0.02mm, var -1.78mm])
  coincident([line1.start, ORIGIN])
  point2 = point(at = [var -2.82mm, var -2.83mm])
  arc1 = arc(start = [var -0.02mm, var -1.78mm], end = [var -3.78mm, var -3.79mm], center = [var 0.32mm, var -6.94mm])
  coincident([point2, arc1])
  arc2 = arc(start = [var -14.91mm, var -3.31mm], end = [var -3.78mm, var -3.79mm], center = [var -9.18mm, var 0.36mm])
  coincident([arc1.end, arc2.end])
  tangent([arc1, arc2])
  line2 = line(start = [var -14.91mm, var -3.31mm], end = [var -14.95mm, var -0.38mm])
  coincident([line2.start, arc2.start])
  line3 = line(start = [var -14.95mm, var -0.38mm], end = [var 0mm, var 0mm])
  coincident([line2.end, line3.start])
  coincident([line3.end, line1.start])
}
```

### Expected Behavior

The camera should orient to the -YZ where the sketch is drawn, instead of the YZ plane.

### Screenshots and Recordings

https://github.com/user-attachments/assets/4debd188-490a-4219-80d6-5a4926454914

### Desktop OS

Ubuntu

### Browser

_No response_

### Version

Staging 26.4.6-main.ad49b96

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by andrewvarga**
Fixes #10847 by adding `default_plane` to `SketchBlock`

Deprecates https://github.com/KittyCAD/modeling-app/pull/11052 which used to parse the default plane, this is cleaner and shorter.

### CODE REVIEW

File: src/lib/selections.ts [hunk 1]
```diff
@@ -1236,18 +1251,16 @@ export async function getPlaneDataFromSketchBlock(
...
   }
 
-  // @pierremtb At the time of writing, this isn't working yet,
-  // so we always go to the next step and treat default planes as offset planes.
-  const defaultResult = getDefaultSketchPlaneData(
-    sketchBlock.planeId,
-    systemDeps
-  )
-  if (!err(defaultResult) && defaultResult) {
-    return defaultResult
```
Comment (andrewvarga) [inline src/lib/selections.ts:1250]: This was removed because it was unused @pierremtb

File: rust/kcl-lib/src/execution/mod.rs [hunk 2]
```diff
@@ -2215,6 +2215,32 @@ secondSolid = extrude(region(point = [2mm, 2mm], sketch = secondProfile), length
         assert!(result.exec_state.issues().is_empty());
     }
 
+    #[cfg(feature = "artifact-graph")]
+    #[tokio::test(flavor = "multi_thread")]
+    async fn sketch_block_artifact_preserves_default_plane_name() {
+        let code = r#"@settings(experimentalFeatures = allow)
```
Comment (jtran) [inline rust/kcl-lib/src/execution/mod.rs]: We don't need this anymore, and we shouldn't use it unless absolutely needed.
```suggestion
        let code = r#"
```

File: rust/kcl-lib/src/execution/artifact.rs [hunk 3]
```diff
@@ -280,7 +281,10 @@ pub struct StartSketchOnPlane {
 #[serde(rename_all = "camelCase")]
 pub struct SketchBlock {
     pub id: ArtifactId,
-    /// The plane ID if the sketch block is on a specific plane, None if it's on a default plane.
+    /// The semantic default plane name when the sketch block is on a default plane.
+    #[serde(default, skip_serializing_if = "Option::is_none")]
+    pub default_plane: Option<PlaneName>,
```
Comment (jtran) [inline rust/kcl-lib/src/execution/artifact.rs]: Nit: Should this be called `standard_plane` instead? I know we call it `Plane::Default(PlaneName)` elsewhere, but I think that was a mistake. My understanding is that the default planes are the specific instances of the standard planes that we create in the engine during a session. But `PlaneName` just says which standard plane. It doesn't have a UUID or anything like that. Maybe @pierremtb has a thought based on how it's used.

Comment (pierremtb) [reply rust/kcl-lib/src/execution/artifact.rs]: standard_plane sounds fine yeah?

Comment (andrewvarga) [reply rust/kcl-lib/src/execution/artifact.rs]: To me that sounds reasonable, I renamed it.

File: rust/kcl-lib/src/execution/mod.rs [hunk 4]
```diff
@@ -2215,6 +2215,32 @@ secondSolid = extrude(region(point = [2mm, 2mm], sketch = secondProfile), length
         assert!(result.exec_state.issues().is_empty());
     }
 
+    #[cfg(feature = "artifact-graph")]
+    #[tokio::test(flavor = "multi_thread")]
+    async fn sketch_block_artifact_preserves_standard_plane_name() {
+        let code = r#"@settings(experimentalFeatures = allow)
```
Comment (pierremtb) [inline rust/kcl-lib/src/execution/mod.rs]: Still one remaining here?

**Review by jtran — APPROVED** [review]

**Review by pierremtb — APPROVED** [review]
Ty!
