### PR TITLE
Fix to display errors at the call site

### LINKED ISSUE #6879: KCL error in another file should be more helpful
Placeholder so we don't forget.

### PR DESCRIPTION
**Pull request by jtran**
Resolves #6879.

I made a `lib.kcl` file that looks like this:

```kcl
export fn check(@x) {
  return assert(x, isGreaterThan = 0)
}
```

Before

Screenshot 2025-05-15 at 8 01 32 PM

Clicking "View error" does nothing.

After

Screenshot 2025-05-15 at 8 01 54 PM

Clicking "View error" moves the cursor to the line with the red underline. Hover displays the message in the tooltip.

When it's in the same file, we also correctly show the call location now.

Before

Screenshot 2025-05-15 at 8 48 25 PM

After

Screenshot 2025-05-15 at 8 11 01 PM

### CODE REVIEW

**Review by jessfraz — APPROVED** [review]

File: src/lang/wasm.ts [hunk 1]
```diff
@@ -230,7 +244,7 @@ export const parse = (code: string | Error): ParseResult | Error => {
     return new KCLError(
       parsed.kind,
       parsed.msg,
-      firstSourceRange(parsed),
+      bestSourceRange(parsed),
```
Comment (jessfraz) [inline src/lang/wasm.ts:247]: why not iterate over them and show multiple i think this is what we used to do?

Comment (jessfraz) [reply src/lang/wasm.ts:247]: i thought there was a playwright test and everything

Comment (jessfraz) [reply src/lang/wasm.ts:247]: ah yeah thats how it was here https://github.com/KittyCAD/modeling-app/pull/2428

Comment (jtran) [reply src/lang/wasm.ts:247]: Because that would display 20 errors, one for each call depth, when there's only 1 error.

Comment (jtran) [reply src/lang/wasm.ts:247]: We support non-fatal errors now, so it's possible to have multiple real errors.

Comment (jessfraz) [reply src/lang/wasm.ts:247]: oh LOL nevermind!!
