### PR TITLE
Visibility toggle for sketch blocks in feature tree

### LINKED ISSUE #10742: Ability to hide sketch block ouput
As discussed in https://kittycadworkspace.slack.com/archives/C09CJ6XPY1Y/p1774990829141219, this is something that's enabled on purpose so that sketch blocks can be reused, but can be in the way of selection. I think this going to lead to so many bug reports.

Image

### PR DESCRIPTION
**Pull request by pierremtb**
Closes #10742. Stacked on #10743 ✅ 

If people are happy with this we may consider applying the `hide(sketch###)` directly on extrusion.

https://github.com/user-attachments/assets/3195316d-9f41-46e0-a937-98a0323f9833

### CODE REVIEW

File: src/components/layout/areas/FeatureTreePane.tsx [hunk 1]
```diff
@@ -937,13 +939,104 @@ const OperationItem = ({
...
       : undefined
-  const hideOperation = operationArtifact
-    ? getHideOpByArtifactId(kclManager.operations ?? [], operationArtifact.id)
-    : undefined
+  const resolvedHideOperation = hideOperationByVariableName ?? hideOperation
+  const unhideTargetArtifact =
+    item.type === 'SketchSolve' ? sketchBlockArtifact : operationArtifact
+  const canToggleVisibility =
+    (item.type === 'StdLibCall' && item.name === 'helix') ||
+    (item.type === 'SketchSolve' && sketchBlockArtifact !== undefined)
```
Comment (pierremtb) [inline src/components/layout/areas/FeatureTreePane.tsx]: I really don't like that Codex added all this convoluted logic here. Will try to improve before we let this go in

File: src/lib/featureTree.spec.ts
Comment (pierremtb) [inline src/lib/featureTree.spec.ts:1]: Codex wrote those, think they're alright?

File: src/lang/std/artifactGraph.ts [hunk 2]
```diff
@@ -777,6 +777,44 @@ export function getFaceCodeRef(
...
+      'codeRef' in artifact &&
+      hasSamePathToNode(artifact.codeRef.pathToNode, pathToNode)
+  )
+}
+
+export function getSketchBlockForPathArtifact(
+  pathArtifact: Extract<Artifact, { type: 'path' }>,
+  artifactGraph: ArtifactGraph
+): Extract<Artifact, { type: 'sketchBlock' }> | undefined {
+  // TODO: replace this pathToNode match once the artifact graph can map a Path to its SketchBlock directly.
```
Comment (pierremtb) [inline src/lang/std/artifactGraph.ts:808]: This is wrapped nicely but still isn't a great way to find the sibbling. Keeping the TODO for now.

File: src/components/layout/areas/FeatureTreePane.tsx [hunk 3]
```diff
@@ -937,13 +933,11 @@ const OperationItem = ({
...
-      ? findOperationArtifact(item, kclManager.artifactGraph)
-      : undefined
-  const hideOperation = operationArtifact
-    ? getHideOpByArtifactId(kclManager.operations ?? [], operationArtifact.id)
-    : undefined
+  const visibilityState = resolveFeatureTreeVisibility({
+    item,
+    operations: kclManager.operations ?? [],
+    artifactGraph: kclManager.artifactGraph,
+  })
```
Comment (franknoirot) [inline src/components/layout/areas/FeatureTreePane.tsx:940]: This is cool

File: src/lang/std/artifactGraph.ts [hunk 4]
```diff
@@ -777,6 +777,44 @@ export function getFaceCodeRef(
   return null
 }
 
+export function hasSamePathToNode(
```
Comment (franknoirot) [inline src/lang/std/artifactGraph.ts:780]: c: I'm a little surprised we don't have a helper for this already

File: src/lang/std/artifactGraph.ts [hunk 5]
```diff
@@ -777,6 +777,44 @@ export function getFaceCodeRef(
...
+export function getSketchBlockForPathArtifact(
+  pathArtifact: Extract<Artifact, { type: 'path' }>,
+  artifactGraph: ArtifactGraph
+): Extract<Artifact, { type: 'sketchBlock' }> | undefined {
+  // TODO: replace this pathToNode match once the artifact graph can map a Path to its SketchBlock directly.
+  return getArtifactsMatchingPathToNode(
+    pathArtifact.codeRef.pathToNode,
+    artifactGraph
+  ).find(
+    (artifact): artifact is Extract<Artifact, { type: 'sketchBlock' }> =>
```
Comment (franknoirot) [inline src/lang/std/artifactGraph.ts:813]: c: I like this type predicate with the `is Extract`, we should use this more.

File: src/lib/featureTree.spec.ts
Comment (franknoirot) [reply src/lib/featureTree.spec.ts:1]: Nice yeah even added coverage to the helix hide behavior, thanks.

File: src/lib/featureTree.ts [hunk 6]
```diff
@@ -1,23 +1,107 @@
...
 import type { modelingMachine } from '@src/machines/modelingMachine'
 import { sourceRangeToUtf16 } from '@src/lang/errors'
 
+export interface FeatureTreeVisibilityState {
+  canToggleVisibility: boolean
+  hideOperation?: HideOperation
+  targetArtifact?: Artifact
+}
+
+export function resolveFeatureTreeVisibility(input: {
```
Comment (franknoirot) [inline src/lib/featureTree.ts:35]: This will be helpful to use in the bodies pane, nice encapsulation.

File: src/lang/std/artifactGraph.ts (hunk 5 above)
Comment (pierremtb) [reply src/lang/std/artifactGraph.ts:813]: Agreed! Was from Codex and I found it great.

File: src/lang/std/artifactGraph.ts (hunk 4 above)
Comment (pierremtb) [reply src/lang/std/artifactGraph.ts:780]: Same!
