### PR TITLE
Bug fix: make "phantom side panes" get properly cleared

### LINKED ISSUE #3779: Phantom panes still open when all panes are closed
https://github.com/user-attachments/assets/5d2e09f2-7891-445e-b503-fa8c2c49d28c

Steps to reproduce
1. close panes
2. move mouse to where resizer was before panes were close
3. see it's still there.

### PR DESCRIPTION
**Pull request by franknoirot**
Fixes #3779 by adding a useEffect that watches the settings and clears out any IDs from our `openPanes` persisted state that should be hidden according to the latest settings. Adds an E2E test for it.

### CODE REVIEW

File: src/components/ModelingSidebar/ModelingSidebar.tsx [hunk 1]
```diff
@@ -24,6 +24,10 @@ interface BadgeInfoComputed {
   onClick?: MouseEventHandler<any>
 }
 
+function getPlatformString(): 'web' | 'desktop' {
+  return isDesktop() ? 'desktop' : 'web'
+}
```
Comment (jtran) [inline src/components/ModelingSidebar/ModelingSidebar.tsx:29]: Hmm, we already use "platform" to mean "OS" (see `src/lib/utils.ts`). Ideally we don't use the same term to talk about multiple things. I think I like this new definition better. We should probably rename the existing uses at some point to `osFamily` or something.

**Review by jtran — APPROVED** [review]
Looks good.

**Comment by Irev-Dev** [comment]
Dope, thank you!
