### PR TITLE
(fix): autoexpand args for `sketch`

### LINKED ISSUE #10168: KCL sketch block should support argument shorthand
I expect sketch block arguments to behave like arguments to any other functions. In particular, argument shorthand where `foo(a)` can be shorthand for `foo(a = a)` should work.

> Sketch blocks cannot have an unlabeled argument. Use a labeled argument instead, like on = `XY`.

Image

### PR DESCRIPTION
**Pull request by therapon**
Allows for `sketch(on)` and expands it into `sketch(on = on)`. This mimics behaviour of other KCL functions and their treatment of arguments. 

Closes #10168

### CODE REVIEW

File: rust/kcl-lib/src/parsing/parser.rs [hunk 1]
```diff
@@ -3857,16 +3870,26 @@ fn fn_call_or_sketch_block(i: &mut TokenSlice) -> ModalResult<Expr> {
...
                     digest: _,
                 },
         } = fn_call;
         if let Some(unlabeled) = unlabeled {
-            ParseContext::err(CompilationIssue::err(
-                unlabeled.into(),
-                "Sketch blocks cannot have an unlabeled argument. Use a labeled argument instead, like `on = XY`.",
-            ));
+            if let Some(label) = sketch_block_arg_shorthand_label(&unlabeled) {
+                arguments.insert(
```
Comment (jtran) [inline rust/kcl-lib/src/parsing/parser.rs:3880]: If they format their code, will it preserve `sketch(on)`?

Comment (therapon) [reply rust/kcl-lib/src/parsing/parser.rs:3880]: No, formatting will "expand" it to `on = on`. 

I'll update.

Comment (therapon) [reply rust/kcl-lib/src/parsing/parser.rs:3880]: Updated PR.

**Review by jtran — APPROVED** [review]
