### PR TITLE
fix symbol rename for unlabeled arg

### LINKED ISSUE #7219: Symbol rename can fail
Image

Try using the rename on run in
```ts
rise = 4.5
run = 8
angle = atan(rise / run)
```

It doesn't work.

Also a paper cut is that it doesn't refocus the editor, requiring it to be clicked back into

### PR DESCRIPTION
**Pull request by jessfraz**
closes #7219

### CODE REVIEW

File: rust/kcl-lib/src/parsing/ast/types/mod.rs [hunk 1]
```diff
@@ -1959,6 +1959,10 @@ impl CallExpressionKw {
     fn rename_identifiers(&mut self, old_name: &str, new_name: &str) {
```
Comment (jtran) [inline rust/kcl-lib/src/parsing/ast/types/mod.rs:1959]: Should `replace_value()` above also recurse into the unlabeled?

Comment (jessfraz) [reply rust/kcl-lib/src/parsing/ast/types/mod.rs:1959]: oh yeah good catch
