### PR TITLE
[SOLVE] Better integrate Sketch Block and Constraints in the Feature Tree

### LINKED ISSUE #9268: Add icons and contextMenu-delete to sketch block constraints
Image

Constraints don't have a icon

And the context menu is wrong

Image

Half these don't make sense even if they are disabled, and "delete" which is enable isn't working.

### PR DESCRIPTION
**Pull request by pierremtb**
Closes #9268 and #9269

In this PR:

- Updated all sketch constraint icons from [Figma](https://www.figma.com/design/5UUPOawPLEs3D0Gptf42vy/Designs?node-id=11185-21910&t=OQAxouvUkHovFLKh-4)
- Added most of the constraints to the feature tree maps with labels and icons:
  - Except Pierce and Curvature from https://github.com/KittyCAD/modeling-app/issues/8169
  - Distance from ezpz is there as well, points to the dimension icon. We'll have to see what #8168 looks like once it's there
  - Normal and more cases for tangent are missing from ezpz I think?
- Wired up right-click Delete on Constraints and Sketch Solve items, with a quick pw test

image

### CODE REVIEW

File: src/lang/modifyAst/deleteFromSelection.ts [hunk 1]
```diff
@@ -153,6 +154,37 @@ export async function deleteFromSelection(
...
+    // Whole sketch block deletion case
+    if (
+      typeof nodeIndex === 'number' &&
+      astClone.body[nodeIndex] !== undefined
+    ) {
+      astClone.body.splice(nodeIndex, 1)
+      return astClone
+    }
+  }
+
```
Comment (pierremtb) [inline src/lang/modifyAst/deleteFromSelection.ts:187]: Just one more case 😬

Comment (pierremtb) [reply src/lang/modifyAst/deleteFromSelection.ts:187]: We surely can move this new deletion case to Rust, but I feel like this is something we could do all at once once we move there?

File: src/lib/operations.ts [hunk 2]
```diff
@@ -1899,6 +1899,58 @@ export const stdLibMap: Record<string, StdLibCallInfo> = {
     supportsAppearance: true,
     supportsTransform: true,
   },
+  'sketch2::coincident': {
```
Comment (Irev-Dev) [inline src/lib/operations.ts:1902]: I think because of https://github.com/KittyCAD/modeling-app/issues/9685 these won't always have the `sketch2` prefix, so maybe add a comment above all these with a link to the issue.

Comment (Irev-Dev) [reply src/lib/operations.ts:1902]: Ah you had auto-merge on, this was just a nit anyway.

**Comment by jtran** [comment]
I thought that deleting the sketch from the Feature Tree would use the new API. Do we support that, but you did it the old way?

- #9328

File: src/lib/operations.ts (hunk 2 above)
Comment (pierremtb) [reply src/lib/operations.ts:1902]: Sorry! Yes totally, guess we'll want to have a big batch replace for sketch2 refs anyways

**Comment by pierremtb** [comment]
@jtran Yeah I agree with the sentiment https://github.com/KittyCAD/modeling-app/pull/9712#discussion_r2699809957

The reason I wired it up the old way was to quickly get a sense of feature tree interactions with constraints and sketch blocks, and see how we should prioritize in-scene rendering and selectability of constraints, without having to get a new deletion code path going.

But yeah that was probably short-sighted and it shouldn't be too hard now that I think about it and I'll be happy to do it in a follow-up. Thanks for the link! How hard would it be to get a similar API for constraint deletion?
