### PR TITLE
Fix: Helix can't be selected as path arg in point-and-click sweep

### LINKED ISSUE #6966: Helix can't be selected as path arg in point-and-click sweep
Point and click sweep fuss

[Slack Message](https://kittycadworkspace.slack.com/archives/C06L2RHP9SL/p1747305143008609?thread_ts=1747305143.008609&cid=C06L2RHP9SL)

### PR DESCRIPTION
**Pull request by pierremtb**
Fixes #6966

### CODE REVIEW

File: src/lib/commandBarConfigs/modelingCommandConfig.ts [hunk 1]
```diff
@@ -425,10 +425,10 @@ export const modelingMachineCommandConfig: StateMachineCommandSetConfig<
       },
       path: {
         inputType: 'selection',
-        selectionTypes: ['segment'],
+        selectionTypes: ['segment', 'helix'],
         required: true,
         multiple: false,
-        validation: sweepValidator,
+        // validation: sweepValidator,
```
Comment (pierremtb) [inline src/lib/commandBarConfigs/modelingCommandConfig.ts:431]: Discussion about removing these for v1:
 https://kittycadworkspace.slack.com/archives/C07A80B83FS/p1747315489085599

cc @franknoirot @nadr0

Comment (pierremtb) [reply src/lib/commandBarConfigs/modelingCommandConfig.ts]: Made a sep PR https://github.com/KittyCAD/modeling-app/pull/6969

**Review by nadr0 — APPROVED** [review]
