### PR TITLE
Fix: Can't go back to Profiles arg in Extrude, Revolve, Loft

### LINKED ISSUE #7080: Can't go back to Profiles step in sweep commands
<@U050E94JUJX> Are you able to go back to the Profiles arg once you've progressed to the next args? I'm not :sad-panda:

[Slack Message](https://kittycadworkspace.slack.com/archives/C04KFV6NKL0/p1747680990065349?thread_ts=1747679002.916189&cid=C04KFV6NKL0)

### PR DESCRIPTION
**Pull request by pierremtb**
Fixes #7080

This fixes a double-fire of the clean up callback calling onSubmit.
And we're back to the non-skip behavior on multi profile sweeps before #7047

### CODE REVIEW

File: src/components/CommandBar/CommandBarSelectionInput.tsx [hunk 1]
```diff
@@ -139,8 +139,8 @@ function CommandBarSelectionInput({
         data: {
           selectionType: 'singleCodeCursor',
         },
-      })
-    setHasClearedSelection(true)
+      }) &&
+      setHasClearedSelection(true)
```
Comment (pierremtb) [inline src/components/CommandBar/CommandBarSelectionInput.tsx:143]: @franknoirot I got it, I think the lack of && here made https://github.com/KittyCAD/modeling-app/blob/7577053189a1f392ed79dab006944b1e52eb58ef/src/components/CommandBar/CommandBarSelectionInput.tsx#L163-L164 fire more than needed and leading to these skips

Comment (pierremtb) [reply src/components/CommandBar/CommandBarSelectionInput.tsx:143]: I noticed after adding this log. With this extra &&, I see it firing only when clicking on other args now.

image

**Review by franknoirot — APPROVED** [review]
I was incorrect about this regressing #7047: that regressed of its own right. I am glad you are improving this.

File: e2e/playwright/editor-tests.spec.ts [hunk 2]
```diff
@@ -1131,9 +1131,8 @@ sketch001 = startSketchOn(XZ)
     await page.waitForTimeout(100)
 
     await page.getByText('startProfile(at = [4.61, -14.01])').click()
-    // Wait for the selection to register (TODO: we need a definitive way to wait for this)
-    await page.waitForTimeout(200)
```
[the remark this answers is not in the document]
Comment (pierremtb) [reply e2e/playwright/editor-tests.spec.ts:1135]: Oh I can re-revert this sorry! Good catch
