### PR TITLE
Fix Shell point-and-click picking the wrong face with piped extrudes

### LINKED ISSUE #4961: [BUG] Shell point and click references the wrong feature
I think this might be an easy fix- the output from the shell button just needs to reference the selected feature instead of the default one.
Also I can't select multiple faces when creating a shell

https://github.com/user-attachments/assets/2d6462c5-4a60-403f-9cad-9b4266c32be2

> _Note: If you are capturing from a browser there is limited support for screenshots, only captures the modeling scene.
  If you are on MacOS native screenshots may be disabled by default. To enable native screenshots add Zoo Modeling App to System Settings -> Screen & SystemAudio Recording for native screenshots._

<details>
<summary><b>Core Dump</b></summary>

[coredump-af3cd7bd-54c3-492f-9236-9e4bdebf455a.json](https://public.blob.zoo.dev/743c60a4-c2f5-4eac-9ada-e548e7c739e6/modeling-app/coredump-af3cd7bd-54c3-492f-9236-9e4bdebf455a.json)

Reference ID: af3cd7bd-54c3-492f-9236-9e4bdebf455a
</details>

<details>
<summary><b>KCL Code</b></summary>

```kcl
sketch001 = startSketchOn('XY')
  |> startProfileAt([6.77, 0], %)
  |> yLine(1.27, %)
  |> tangentialArcTo([5.96, 2.37], %)
  |> tangentialArcTo([-6.2, 2.44], %)
  |> tangentialArcTo([-6.6, 1.82], %)
  |> yLine(-1.82, %)
  |> close(%)
  // |> mirror2d({ axis = "X" }, %)
  |> extrude(10, %)

sketch002 = startSketchOn(sketch001, 'END')
  |> circle({ center = [-0.01, 1.58], radius = 1.2 }, %)
  |> extrude(1.2, %)

// shell({ faces = ['end'], thickness = .1 }, [sketch002])

shell001 = shell({ faces = ['end'], thickness = .1 }, sketch001)

```
</details>

### PR DESCRIPTION
**Pull request by pierremtb**
Fixes #4961 and add test coverage for sketch on face extrude (both with and without piped extrudes).

### CODE REVIEW

**Comment by pierremtb** [comment]
Crap the e2e failures are real, was able to reproduce on Ubuntu, investigating...

File: src/lang/modifyAst/addShell.ts [hunk 1]
```diff
@@ -92,6 +102,8 @@ export function addShell({
     pathToExtrudeNode,
     'VariableDeclarator'
   )
+  console.log('pathToExtrudeNode', pathToExtrudeNode)
+  console.log('extrudeNode', extrudeNode)
```
Comment (franknoirot) [inline src/lang/modifyAst/addShell.ts:106]:
```suggestion
```
[nit] could probably remove unless you want these in for a short while for production visibility?

**Review by franknoirot — APPROVED** [review]
Nice nice, confirmed this is working as expected, thanks for the added test case

Screenshot 2025-01-09 at 3 38 29 PM

File: src/lang/modifyAst/addShell.ts (hunk 1 above)
Comment (pierremtb) [reply src/lang/modifyAst/addShell.ts]: Thanks Frank!
