### PR TITLE
KCL: Fix two cryptic error messages

### LINKED ISSUE #5647: [CRYPTIC]: Error: Failed to stopAt undefined, We > file:///Applications/Zoo%20Modeling%20App.app/Contents/Resources/app.asar/.vite/renderer/main_window/assets/index-BovgrvGq.js:4940:25087
### Paste minimal KCL source that produces a cryptic error

```javascript
pinHoleDiameter = 0.76
thickness = 0.25

sketch001 = startSketchOn('XZ')
profile001 = circle({ center = [0, 0], radius =  }, sketch001)
profile002 = circle({ center = [0, 0], radius =  }, sketch001)
```

### Expected Behavior

I do expect an error, but not the cryptic one I got. 

### Additional Context

This happens when you are in the sketch. I used two profiles that are circles, and weird errors would show up if I left the radii blank

https://github.com/user-attachments/assets/90cd8f89-38ef-4ac4-92f8-c982e7b15dac

### PR DESCRIPTION
**Pull request by adamchalmers**
Firstly, before the code "{x = 1, y = }" would give the dreaded "unexpected token" error.

Now it says "This property has a label, but no value. Put some value after the equals sign". And points to the = symbol with no matching right-hand side value. Yay!

Second fix: before, in the code `f(1, x=)`, the error complained that an unlabeled arg was not permitted there.

Now it says "This argument has a label, but no value. Put some value after the equals sign".

Closes #5647

### CODE REVIEW

File: rust/kcl-lib/src/parsing/parser.rs [hunk 1]
```diff
@@ -2821,6 +2834,7 @@ fn fn_call_kw(i: &mut TokenSlice) -> PResult<Node<CallExpressionKw>> {
         alt((
             terminated(non_code_node.map(ArgPlace::NonCode), whitespace),
             terminated(labeled_argument, labeled_arg_separator).map(ArgPlace::LabeledArg),
+            terminated(expression, (opt(whitespace), equals)).map(ArgPlace::LabelWithoutRhs),
```
Comment (jtran) [inline rust/kcl-lib/src/parsing/parser.rs:2837]: This can backtrack a lot. Are you sure you want to do this?

Comment (jtran) [reply rust/kcl-lib/src/parsing/parser.rs:2837]: Maybe this can be merge with the line below.

**Review by jessfraz — APPROVED** [review]

File: rust/kcl-lib/src/parsing/parser.rs (hunk 1 above)
Comment (adamchalmers) [reply rust/kcl-lib/src/parsing/parser.rs:2837]: This is the performance difference (I ran on my branch then on main, so treat the "performance gains" as performance losses). 3-4% slowdown on the really long programs is OK IMO.

Screenshot 2025-03-11 at 12 48 38 PM

Comment (adamchalmers) [reply rust/kcl-lib/src/parsing/parser.rs]: OK I merged it with the line below.

**Review by nrc — APPROVED** [review]
