### PR TITLE
[BUG] offsetPlane back-side startSketchOn

### LINKED ISSUE #4525: Offsetting a negative plane flips the plane
Offsetting a plane with a sketch drawn on the negative side will flip the sketch across the axis. This happens regardless of whether the offset distance is negative or positive.

https://github.com/user-attachments/assets/57056c24-f55e-4995-90ea-8b0f1e366380

<details>
<summary><b>Core Dump</b></summary>

[coredump-bbe56263-4955-463a-8e93-3cef0361cef2.json](https://public.blob.zoo.dev/a0f3a148-4143-41a5-9445-b3f66915fff3/modeling-app/coredump-bbe56263-4955-463a-8e93-3cef0361cef2.json)

Reference ID: bbe56263-4955-463a-8e93-3cef0361cef2
</details>

<details>
<summary><b>KCL Code</b></summary>

```ts
// Define Latch Handle


sheetThickness = .040
bendRad = 0.040
latchWidth = 1 + 7 / 8
latchLength = 3

fn baseSketch(width) {
  sketch001 = startSketchOn(offsetPlane(XY, offset=width))
    |> startProfileAt([0, bendRad + sheetThickness], %)
    |> yLine(length=0.21, tag=$edge1)
    |> arc(
         angleStart= 270,
         angleEnd= 90,
         radius= .25
       )
    |> xLine(length=1.04)
    |> arc(
         angleStart= 90,
         angleEnd= 0,
         radius= 0.25
       )
    |> xLine(endAbsolute=latchLength)
    |> yLine(endAbsolute=bendRad + sheetThickness)
    |> line(endAbsolute=[profileStartX(%), profileStartY(%)])
    |> close(%)
    |> hole(circle( center= [0, .55], radius= .25 / 2 ), %)
    |> hole(circle( center= [1, .55], radius= .25 / 2 ),%)
    |> extrude(length=sheetThickness)

  return sketch001
}
baseSketch(0)

sketch002 = startSketchOn(-YZ)
  |> startProfileAt([
       -bendRad - sheetThickness,
       sheetThickness
     ], %)
  |> arc(
       angleStart= -90,
       angleEnd= 0,
       radius= bendRad
     )
  |> xLine(length=sheetThickness)
  |> arc(
       angleStart = 0,
       angleEnd = -90,
       radius = bendRad + sheetThickness
     )
  |> line(endAbsolute=[profileStartX(%), profileStartY(%)])
  |> close()
extrude002 = extrude(sketch002, length=-latchLength)
sketch003 = startSketchOn(XZ)
  |> startProfileAt([0, bendRad + sheetThickness], %)
  |> angledLine(angle=0, length=latchLength, tag=$rectangleSegmentA001)
  |> angledLine(angle=segAng(rectangleSegmentA001) + 90, 
       length=latchWidth - (2 * bendRad) - (2 * sheetThickness), 
       
       tag=$rectangleSegmentB001)
  |> angledLine(angle=segAng(rectangleSegmentA001),
       length=-segLen(rectangleSegmentA001),
       
       tag=$rectangleSegmentC001)
  |> line(endAbsolute=[profileStartX(%), profileStartY(%)])
  |> close()
extrude003 = extrude(sketch003, length=-sheetThickness)

sketch004 = startSketchOn(-YZ)
  |> startProfileAt([
       -sheetThickness,
       latchWidth - bendRad - sheetThickness
     ], %)
  |> arc(
       angleStart = 0,
       angleEnd = 90,
       radius = bendRad
     )
  |> yLine(length=sheetThickness)
  |> arc(
       angleStart= 90,
       angleEnd= 0,
       radius= bendRad + sheetThickness
     )
  |> line(endAbsolute=[profileStartX(%), profileStartY(%)])
  |> close()
extrude004 = extrude(sketch004, length=-latchLength)
baseSketch(latchWidth - sheetThickness)

// Define Simple Clevis Pin
sketch005 = startSketchOn(XY)
  |> circle(center= [1, 0.55], radius= 0.563 / 2 )

extrude001 = extrude(sketch005, length=-0.35)
sketch006 = startSketchOn(XY)
  |> circle(center= [1, 0.55], radius= 0.25 / 2 )
extrude005 = extrude(sketch006, length=2.5)

sketch007 = startSketchOn(offsetPlane(XZ, offset=-.55))
  |> startProfileAt([.875, 0], %)
  |> xLine(length=-1.625)
  |> yLine(length=1.875)
  |> xLine(length=1.625 + .5)
  |> yLine(length=0.1)
  |> xLine(length=-1.625 - .1 - .5)
  |> yLine(length=-1.875 - .2)
  |> xLine(length=1.625 + .1)
  |> line(endAbsolute=[profileStartX(%), profileStartY(%)])
  |> close()
extrude006 = extrude(sketch007, length=.1)

sketch008 = startSketchOn(offsetPlane(-YZ, offset=1))
  |> startProfileAt([-0.19, 0.08], %)
  |> xLine(length=-0.77)
  |> yLine(length=1.67)
  |> xLine(length=0.73)
  |> yLine(length=-0.08)
  |> xLine(length=-0.63)
  |> yLine(length=-1.49)
  |> xLine(length=0.67)
  |> line(endAbsolute=[profileStartX(%), profileStartY(%)])
  |> close()


```
</details>

### PR DESCRIPTION
**Pull request by Irev-Dev**
Resolves #4525

https://github.com/user-attachments/assets/d45f6250-e513-4449-b10a-3b2d01edf1c9

This PR implements a fix for issue #4525 - "Offsetting a negative plane flips the plane". The core issue was that when sketching on offset planes, the orientation logic wasn't properly determining which side of the plane was clicked, causing sketches to appear flipped.

changes:

- Fixed offset plane orientation detection by implementing camera-based logic similar to default planes
- Updated KCL code generation to properly generate `-plane001` when sketching on the back side of offset planes
- Copy pasted `Can create sketches on all planes and their back sides` tests and tweaks to test this as well
- added missing aria-label attributes to custom icons (needed one for tests, but figured would be good to fix them all)

### CODE REVIEW

File: src/hooks/useEngineConnectionSubscriptions.ts [hunk 1]
```diff
@@ -164,20 +164,49 @@ export function useEngineConnectionSubscriptions() {
...
+                  Math.abs(zAxis[2]),
+                ]
+
+                // Find the dominant axis (like default planes do)
+                const maxComponent = Math.max(...absZAxis)
+                const dominantAxisIndex = absZAxis.indexOf(maxComponent)
+
+                // Check camera position against canonical orientation (like default planes)
+                const cameraComponents = [camVector.x, camVector.y, camVector.z]
+                let negated = cameraComponents[dominantAxisIndex] < 0
```
Comment (Irev-Dev) [inline src/hooks/useEngineConnectionSubscriptions.ts:198]: We can tell which side of the plane they are on if the cameraComponent along the normal of the plane is < 0 or not.

File: src/hooks/useEngineConnectionSubscriptions.ts [hunk 2]
```diff
@@ -164,20 +164,49 @@ export function useEngineConnectionSubscriptions() {
...
+                if (dominantAxisIndex === 1) {
+                  // offset of the XZ is being weird, not sure if this is a camera bug
+                  negated = !negated
```
Comment (Irev-Dev) [inline src/hooks/useEngineConnectionSubscriptions.ts:201]: So gross!

But I had to make it work, I have no idea why XZ is different.

I'll ping @davreev  and @nadr0  about this, in case it somehow camera related.

File: src/lang/modifyAst.ts [hunk 3]
```diff
@@ -728,18 +730,19 @@ export function sketchOnOffsetPlane(
   const { node: offsetPlaneNode } = offsetPlaneDeclarator
   const offsetPlaneName = offsetPlaneNode.id.name
 
+  // Create the plane argument - either the plane name or negated plane name
+  const planeArgument = negated
+    ? createUnaryExpression(createLocalName(offsetPlaneName), '-')
+    : createLocalName(offsetPlaneName)
```
Comment (Irev-Dev) [inline src/lang/modifyAst.ts:736]: generates `startSketchOn(-planeXXX)` when needed

File: src/components/CustomIcon.tsx [hunk 4]
```diff
@@ -107,7 +107,12 @@ const CustomIconMap = {
     </svg>
   ),
   beaker: (
-    <svg viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
+    <svg
+      viewBox="0 0 20 20"
+      fill="none"
+      xmlns="http://www.w3.org/2000/svg"
+      aria-label="beaker"
```
Comment (pierremtb) [inline src/components/CustomIcon.tsx:114]: Nice, were those auto generated by a tool?

File: src/hooks/useEngineConnectionSubscriptions.ts (hunk 2 above)
Comment (pierremtb) [reply src/hooks/useEngineConnectionSubscriptions.ts:201]: Damn yeah good find and will be good to find the root cause

File: src/lang/modifyAst.ts (hunk 3 above)
Comment (pierremtb) [reply src/lang/modifyAst.ts:736]: Had to go look at the definition haha, it's so counterintuitive to me to have the sign after, but all good here.

File: src/components/CustomIcon.tsx (hunk 4 above)
Comment (Irev-Dev) [reply src/components/CustomIcon.tsx:114]: I just told AI to grab the key and use that as the label. so kinda. but not a deterministic tool we'd want to use as a lint haha.

File: src/lang/modifyAst.ts (hunk 3 above)
Comment (Irev-Dev) [reply src/lang/modifyAst.ts:736]: Oh that's a good point, That's probaby my fault.

Looks like I forgot that `'-'` is the default so I could have just made this `createUnaryExpression(createLocalName(offsetPlaneName))` but not worth waiting for CI again.

File: src/components/CustomIcon.tsx (hunk 4 above)
Comment (franknoirot) [reply src/components/CustomIcon.tsx:114]: Slick
