### PR TITLE
More consistent error handling in modelingMachine codemods

### LINKED ISSUE #6514: More consistent error handling in modelingMachine codemods
Alright these are super valid. Just now I specifically tried to mess around with cases that would trigger that it it would fail silently. Turned out I needed two things to make the errors show up:
1. change from `return new Error(...` to `return Promise.reject(new Error(...` as you suggested
2. change `'Applying clone'`'s `onError` from `onDone: ['idle']` to `onError: { target: 'idle', actions: 'toastError' }`, which of course makes sense!
 
Pushed these changes here, and I'll create a follow up issue to make some of the other codmods that are likely to have silent errors have those changes as well

_Originally posted by @pierremtb in https://github.com/KittyCAD/modeling-app/pull/6478#discussion_r2061268005_

### LINKED ISSUE #6900: Bug: Starting a new sketch on execution error clears the editor
Starting a new sketch on execution error clears the editor

https://github.com/user-attachments/assets/1c101324-b07e-4324-a4fe-c9a1d5e3db89

[Slack Message](https://kittycadworkspace.slack.com/archives/C06L2RHP9SL/p1747144555889499?thread_ts=1747144555.889499&cid=C06L2RHP9SL)

### PR DESCRIPTION
**Pull request by pierremtb**
Closes #6514 and fixes #6900 (P0).

Upgraded:
- all sweeps
- all edge treatments and shell
- all booleans
- offset plane and helix
- all assemblies transform
- insert and edit parameter

to have:

- consistent fromPromise typing
- consistent Promise.reject(Error) return behavior
- the existing 'no kcl errors' guard
- onError trigger toastError

Also added the 'no kcl errors' guard to enter sketch.

And @franknoirot made all those buttons and commands disabled based on the `.can` transition check 🙌

### CODE REVIEW

File: src/machines/modelingMachine.ts [hunk 1]
```diff
@@ -3096,50 +3162,74 @@ export const modelingMachine = setup({
             target: 'animating to existing sketch',
             guard: 'Selection is on face',
           },
-          'Sketch no face',
+          {
+            target: 'Sketch no face',
+            guard: 'no kcl errors',
+          },
```
Comment (pierremtb) [inline src/machines/modelingMachine.ts:3168]: Not entirely sure if this is how we should do it but it seems to work?

File: src/machines/modelingMachine.ts [hunk 2]
```diff
@@ -3164,41 +3254,44 @@ export const modelingMachine = setup({
...
+          guard: 'no kcl errors',
+        },
+        'Boolean Union': {
+          target: 'Boolean uniting',
+          guard: 'no kcl errors',
+        },
+        'Boolean Intersect': {
+          target: 'Boolean intersecting',
+          guard: 'no kcl errors',
+        },
```
Comment (pierremtb) [inline src/machines/modelingMachine.ts:3294]: I noticed those don't have `reenter: true` compared to all the others

File: src/machines/modelingMachine.ts [hunk 3]
```diff
@@ -4547,7 +4664,10 @@ export const modelingMachine = setup({
               return event.data
             },
             onDone: ['#Modeling.idle'],
-            onError: ['#Modeling.idle'],
+            onError: {
+              target: '#Modeling.idle',
+              actions: 'toastError',
+            },
```
Comment (pierremtb) [inline src/machines/modelingMachine.ts:4670]: Those two were doing fancy # business, not sure what's up

File: e2e/playwright/sketch-tests.spec.ts [hunk 4]
```diff
@@ -1365,18 +1365,18 @@ solid001 = subtract([extrude001], tools = [extrude002])
...
-  const railClampable = in2mm(.200)
+  railTop = in2mm(.748)
+  railSide = in2mm(.024)
+  railBaseWidth = in2mm(.612)
+  railWideWidth = in2mm(.835)
+  railBaseLength = in2mm(.200)
+  railClampable = in2mm(.200)
 
-  const rail = startSketchOn(XZ)
+  rail = startSketchOn(XZ)
```
Comment (pierremtb) [inline e2e/playwright/sketch-tests.spec.ts:1379]: This outdated KCL here was actually leading to errors, and showcasing the very overwrite behavior that this PR is trying to fix at 00:30 in the video below


https://github.com/user-attachments/assets/05a74204-c6d3-4711-854b-4e4d3954208f

File: src/machines/modelingMachine.ts [hunk 5]
```diff
@@ -578,7 +581,9 @@ export const modelingMachine = setup({
     'has valid selection for deletion': () => false,
     'is-error-free': () => false,
     'no kcl errors': () => {
-      return !kclManager.hasErrors()
+      const hasErrors = kclManager.hasErrors()
+      if (hasErrors) toast.error(KCL_ERRORS_MESSAGE)
```
Comment (pierremtb) [inline src/machines/modelingMachine.ts:585]: Toasting in here is probably anti-pattern, but this hasn't led to any side effect in my testing and I'm a little out of options here?

File: src/machines/modelingMachine.ts [hunk 6]
```diff
@@ -1775,76 +1785,167 @@ export const modelingMachine = setup({
...
+     * trigger toastError on Error, and have the 'no kcl errors' guard yet */
+    extrudeAstMod: fromPromise(
+      async ({
+        input,
+      }: {
+        input: ModelingCommandSchema['Extrude'] | undefined
+      }) => {
+        if (!input) {
+          return Promise.reject(new Error(NO_INPUT_PROVIDED_MESSAGE))
         }
```
Comment (pierremtb) [inline src/machines/modelingMachine.ts:1872]: These are just moved from below, no change

File: src/machines/modelingMachine.ts [hunk 7]
```diff
@@ -2541,79 +2670,6 @@ export const modelingMachine = setup({
...
-        return {} as SketchDetailsUpdate
-      }
-    ),
-    'submit-prompt-edit': fromPromise(
-      async ({
-        input,
-      }: {
-        input: ModelingCommandSchema['Prompt-to-edit']
-      }) => {}
-    ),
```
Comment (pierremtb) [inline src/machines/modelingMachine.ts:2616]: Those are just moved up, see previous message

File: src/machines/modelingMachine.ts [hunk 8]
```diff
@@ -3096,50 +3172,74 @@ export const modelingMachine = setup({
...
           target: 'Applying extrude',
           reenter: true,
+          guard: 'no kcl errors',
+        },
+
+        Sweep: {
+          target: 'Applying sweep',
+          reenter: true,
+          guard: 'no kcl errors',
+        },
```
Comment (pierremtb) [inline src/machines/modelingMachine.ts:3191]: Doing just a tiny bit of reordering here and below for consistency

File: e2e/playwright/code-pane-and-errors.spec.ts [hunk 9]
```diff
@@ -179,7 +179,7 @@ extrude001 = extrude(sketch001, length = 5)`
     await page.setBodyDimensions({ width: 1200, height: 500 })
     await homePage.goToModelingScene()
 
-    await scene.settled(cmdBar)
```
Comment (pierremtb) [inline e2e/playwright/code-pane-and-errors.spec.ts:182]: We can't use `scene.settled` anymore on bad kcl since the Start Sketch button will never be enabled @franknoirot. Guess I could update the fixture? 👀

File: e2e/playwright/regression-tests.spec.ts [hunk 10]
```diff
@@ -40,7 +41,8 @@ test.describe('Regression tests', () => {
     await page.setBodyDimensions({ width: 1000, height: 500 })
 
     await homePage.goToModelingScene()
-    await u.waitForPageLoad()
```
Comment (pierremtb) [inline e2e/playwright/regression-tests.spec.ts:43]: Same for this guy

File: src/Toolbar.tsx [hunk 11]
```diff
@@ -158,7 +158,8 @@ export function Toolbar({
       const isDisabled =
         disableAllButtons ||
         !isConfiguredAvailable ||
-        maybeIconConfig.disabled?.(state) === true
+        maybeIconConfig.disabled?.(state) === true ||
+        kclManager.hasErrors()
```
Comment (pierremtb) [inline src/Toolbar.tsx:162]: @franknoirot I think I'd like to wrap `hasErrors()` here in some `hasNoKclErrors(kclManager)` function or something like that so we can edit it in one place if need be

File: src/machines/modelingMachine.ts [hunk 12]
```diff
@@ -578,7 +580,8 @@ export const modelingMachine = setup({
     'has valid selection for deletion': () => false,
     'is-error-free': () => false,
     'no kcl errors': () => {
-      return !kclManager.hasErrors()
+      const hasErrors = kclManager.hasErrors()
+      return !hasErrors
```
Comment (pierremtb) [inline src/machines/modelingMachine.ts:584]: https://github.com/KittyCAD/modeling-app/pull/6910/files#r2089843309 and like reusing it here as well

**Comment by nadr0** [comment]
I tested with the commands in the feature tree and those do not go through :+1:

**Review by nadr0 — APPROVED** [review]
I tested locally and I was not able to figure out a way to delete my code via the empty ast + code mod. This looks like a great guard.

Awesome work on this Pierre.
