### PR TITLE
[BUG] circle and threePointArc and other overlay fixes

### LINKED ISSUE #6203: Circle sketch tool regression: center and radius constraints
> The center position is not available for constraining, the length is not displayed in the overlay properly

 _Originally posted by @franknoirot in [#6090](https://github.com/KittyCAD/modeling-app/issues/6090#issuecomment-2769553544)_

### LINKED ISSUE #6475: Overlays and remove constraint should work for arc()
Since #6334, the overlays that display the constraints of an arc and the ability to remove the constraints has been broken.

### PR DESCRIPTION
**Pull request by Irev-Dev**
Stuff that broke in kwarg migration, obviously didn't have a test. I'll fix that too.

Resolves #6203 
P0 bug☝️ 

- [x] Constrain the radius via overlay was completely busted because it was trying to use a object (non kwargs)
- [x] dido for unconstraining
- [x] X & Y overlays did not display because path to node was wrong (updated incorrectly during kwargs migration - missing 'elements')
- [x] tests for the above

## scope creep
- [x] I found that three point arc overlays broke in https://github.com/KittyCAD/modeling-app/pull/6334 (they must not have had tests), Fixed in this PR too. Fixes #6475.
- [x] I found that tangential Arc remove constraints via the overlays also broke (probably in kwarg migration)
- [x] Add a test for this as well

### CODE REVIEW

File: src/clientSideScene/ClientSideSceneComp.tsx [hunk 1]
```diff
@@ -4,6 +4,10 @@ import toast from 'react-hot-toast'
 
 import type { Node } from '@rust/kcl-lib/bindings/Node'
 
+// Helper function to check if overlays should always be shown
+const shouldAlwaysShowOverlays = () =>
+  localStorage.getItem('showAllOverlays') === 'true'
+
```
Comment (Irev-Dev) [inline src/clientSideScene/ClientSideSceneComp.tsx:10]: @franknoirot I added logic for turning all of the overlays at the start of a test, I have not migrated any existing tests over to this though yet.

File: src/components/CustomIcon.tsx [hunk 2]
```diff
@@ -628,8 +628,8 @@ const CustomIconMap = {
       xmlns="http://www.w3.org/2000/svg"
     >
       <path
-        fill-rule="evenodd"
-        clip-rule="evenodd"
+        fillRule="evenodd"
+        clipRule="evenodd"
```
Comment (Irev-Dev) [inline src/components/CustomIcon.tsx:632]: Unrelated console noise fix.

File: src/components/Loading.tsx [hunk 3]
```diff
@@ -137,7 +137,8 @@ const Loading = ({ children, className, dataTestId }: LoadingProps) => {
             __html: Marked.parse(
               CONNECTION_ERROR_TEXT[error.error] +
                 (error.context
-                  ? '\n\nThe error details are: ' + error.context
+                  ? '\n\nThe error details are: ' +
+                    JSON.stringify(error.context)
```
Comment (Irev-Dev) [inline src/components/Loading.tsx:141]: Unrelated, I hit this error and it reads `The error details are: [object: Object]` figure it was better that it's somewhat readable.

File: src/lang/std/sketch.ts [hunk 4]
```diff
@@ -100,7 +100,7 @@ import type { EdgeCutInfo } from '@src/machines/modelingMachine'
 const STRAIGHT_SEGMENT_ERR = new Error(
   'Invalid input, expected "straight-segment"'
 )
-const ARC_SEGMENT_ERR = new Error('Invalid input, expected "arc-segment"')
+const ARC_SEGMENT_ERR = () => new Error('Invalid input, expected "arc-segment"')
```
Comment (Irev-Dev) [inline src/lang/std/sketch.ts:103]: It's really hard to trace where the error was returned when the same error is used everywhere, making this a function fixes that.

File: src/components/CustomIcon.tsx (hunk 2 above)
Comment (jtran) [reply src/components/CustomIcon.tsx:632]: This should have been merged by #6418.

File: e2e/playwright/testing-segment-overlays.spec.ts [hunk 5]
```diff
@@ -1463,4 +1463,328 @@ part001 = startSketchOn(XZ)
...
+profile001 = circleThreePoint(
+  sketch001,
+  p1 = [445.16, 202.16],
+  p2 = [445.16, 116.92],
+  p3 = [546.85, 103],
+)
+profile003 = startProfileAt([64.39, 35.16], sketch001)
+  |> line(end = [60.69, 23.02])
+  |> arc(interiorAbsolute = [159.26, 100.58], endAbsolute = [237.05, 84.07])
+  |> line(end = [70.31, 42.28])`
```
Comment (jtran) [inline e2e/playwright/testing-segment-overlays.spec.ts:1619]: I think something's not right. I checked out this branch and entered this code to try to verify. I'm seeing overlays are still unconstrained on the arc, and I see this in the console.

Screenshot 2025-04-24 at 11 08 55 AM

Comment (Irev-Dev) [reply e2e/playwright/testing-segment-overlays.spec.ts:1611]: Hmm, I don't seem to be able to replicate.

Comment (Irev-Dev) [reply e2e/playwright/testing-segment-overlays.spec.ts:1611]: https://github.com/user-attachments/assets/bfb73733-e6dd-40b9-bb4a-5dd6b6cb07c7

Were there any steps in particular you used to trigger this?

Comment (Irev-Dev) [reply e2e/playwright/testing-segment-overlays.spec.ts:1611]: This is fixed now, thanks guys.

**Review by pierremtb — APPROVED** [review]
Ty for looking at the issue!
