### PR TITLE
#9407 Fix unclickable cube gizmo face when reduced motion is enabled in macOS

### LINKED ISSUE #9407: [BUG]: Gizmo navigation is not starting with Apple reduced motion
### Describe the bug

If reduced motion (search in Apple macOS settings) is enabled the antimation does not start/finish.

https://github.com/KittyCAD/modeling-app/blob/6b968ad675f573e036635371fa414976d4592b3c/src/clientSideScene/CameraControls.ts#L1317-L1327

There is an early return which does not move to the final state.

### Steps to Reproduce

1. Enable reduced motion
2. Click any side of the gizmo

### Expected Behavior

The view just instantly moves to the resulting view.

### Screenshots and Recordings

_No response_

### Desktop OS

macOS

### Browser

_No response_

### Version

latest

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by andrewvarga**
Fixes #9407

### CODE REVIEW

File: src/clientSideScene/CameraControls.ts [hunk 1]
```diff
@@ -1239,15 +1241,14 @@ export class CameraControls {
       if (isReducedMotion()) {
         // eslint-disable-next-line @typescript-eslint/no-floating-promises
         onComplete()
-        return
+      } else {
```
Comment (andrewvarga) [inline src/clientSideScene/CameraControls.ts:1235]: I just reorganized the end of the function, I think it's visually clearer to see these 2 different branches with the explicit else branch as opposed to the previous early return.

File: src/clientSideScene/CameraControls.ts [hunk 2]
```diff
@@ -1230,6 +1230,8 @@ export class CameraControls {
           this.useOrthographicCamera()
         } else if (toOrthographic) {
           await this.animateToOrthographic()
+        } else {
+          cameraAtTime(0.9999)
```
Comment (andrewvarga) [inline src/clientSideScene/CameraControls.ts]: This is the actual fix, `cameraAtTime` needs to be called for the camera to be updated, even if there is no animation.

File: src/clientSideScene/CameraControls.ts [hunk 3]
```diff
@@ -1230,6 +1230,8 @@ export class CameraControls {
           this.useOrthographicCamera()
         } else if (toOrthographic) {
           await this.animateToOrthographic()
```
Comment (andrewvarga) [inline src/clientSideScene/CameraControls.ts]: `toOrthographic` is never true currently because `animateToOrthographic()` didn't work well, but I kept the code around in case if it's ever going to be needed. However if I get confirmation it's not needed - and I don't see any problems without it - we can remove that too along with `animateToOrthographic`.

File: src/clientSideScene/CameraControls.ts (hunk 2 above)
Comment (maxammann) [reply src/clientSideScene/CameraControls.ts]: why is this not 1? else looks good!

File: src/clientSideScene/CameraControls.ts (hunk 3 above)
Comment (maxammann) [reply src/clientSideScene/CameraControls.ts]: maybe worth adding as comment

File: src/clientSideScene/CameraControls.ts (hunk 2 above)
Comment (andrewvarga) [reply src/clientSideScene/CameraControls.ts]: I thought there was a reason we were using 0.9999 already a few lines above, but I tested and I don't see problems with 1 either. I changed both to 1.
If that breaks anything and we need to use 0.9999 again I will add some comments about it.

File: src/clientSideScene/CameraControls.ts (hunk 3 above)
Comment (andrewvarga) [reply src/clientSideScene/CameraControls.ts]: Good point!

Comment (andrewvarga) [reply src/clientSideScene/CameraControls.ts]: I investigated on git, this wasn't even used before the cubegizmo so I've removed it along with the unused functions.
