### PR TITLE
fix vertex selection

### LINKED ISSUE #834: move lines is broken w xstate stuff
- [x] edit sketch cannot move more than once
- [x] inital sketch move not updating code
- [x] Make vertex selection work again #869 

https://github.com/KittyCAD/modeling-app/assets/1445228/a0380130-c3cb-4573-a7db-efdbc04d81f7

### PR DESCRIPTION
**Pull request by Irev-Dev**
Resolves #834 (last bullet point)

Something I still don't love about this but not directly related (being in edit mode has issues if there's a re-execution etc, but they are for more fixes to come along soon)

I created #868 in the process, just something to be aware of.

### CODE REVIEW

File: src/components/ModelingMachineProvider.tsx [hunk 1]
```diff
@@ -282,7 +282,7 @@ export const ModelingMachineProvider = ({
         }
         // This DOES NOT set the `selectionRanges` in xstate context
         // same as comment above
-        const selectionRangeTypeMap = dispatchCodeMirrorCursor({
+        const { selectionRangeTypeMap } = dispatchCodeMirrorCursor({
```
Comment (Irev-Dev) [inline src/components/ModelingMachineProvider.tsx:285]: This was a bug that I'm shocked that typescript didn't pick up on, seems bizarre to me.
