### PR TITLE
Nickmccleery/fix top bottom default views

### LINKED ISSUE #5654: [BUG]: View Control Menu Yields Incorrect Orientation for 'Top' and 'Bottom'
### Describe the bug

When using the modelling app, selecting either 'Top' or 'Bottom' options from the view helper gizmo's menu yields a view that is parallel to the target (XY) plane, but 90° rotated (around Z) from expected.

I was about to raise this as a ticket on engine, but I've had a trawl through the modelling app code and think it _might_ in here. Looks like relevant sections are:
- `VIEW_NAMES_SEMANTIC` in `modeling-app/src/lib/constants.ts`.
- Calls to `updateCameraToAxis` in `modeling-app/src/components/ViewControlMenu.tsx`.
- `updateCameraToAxis` making `default_camera_look_at` requests in `modeling-app/src/clientSideScene/CameraControls.ts`.

What I see is that we list `up` as negative X for both top and bottom, but I _think_ up should be positive Y.

```
...
    if (axis === 'x') {
      vantage.x += distance
    } else if (axis === 'y') {
      vantage.y += distance
    } else if (axis === 'z') {
      vantage.z += distance
      up = { x: -1, y: 0, z: 0 }
    } else if (axis === '-x') {
      vantage.x -= distance
    } else if (axis === '-y') {
      vantage.y -= distance
    } else if (axis === '-z') {
      vantage.z -= distance
      up = { x: -1, y: 0, z: 0 }
    }
...
```

->

```
...
    if (axis === 'x') {
      vantage.x += distance
    } else if (axis === 'y') {
      vantage.y += distance
    } else if (axis === 'z') {
      vantage.z += distance
      up = { x: 0, y: 1, z: 0 }
    } else if (axis === '-x') {
      vantage.x -= distance
    } else if (axis === '-y') {
      vantage.y -= distance
    } else if (axis === '-z') {
      vantage.z -= distance
      up = { x: 0, y: 1, z: 0 }
    }
...
```

### Steps to Reproduce

1. Load KCL below.
2. Navigate as you like.
3. Use 'Top' or 'Bottom' buttons via view helper gizmo.
4. See that view is 90° out from expectation.

Sample KCL:

```
sketch001 = startSketchOn(XY)
  |> startProfileAt([-152.675, -60.174], %)
  |> bezierCurve({
      control1 = [7.315, 27.416],
      control2 = [19.758, 53.186],
      to = [34.257, 77.476]
    }, %)
  |> bezierCurve({
      control1 = [61.709, 97.431],
      control2 = [142.648, 187.572],
      to = [247.543, 239.024]
    }, %)
  |> bezierCurve({
      control1 = [6.274, 3.088],
      control2 = [12.508, 6.284],
      to = [19, 8.9]
    }, %)
  |> bezierCurve({
      control1 = [48.485, -43.813],
      control2 = [94.592, -90.15],
      to = [142.1, -135]
    }, %)
  |> bezierCurve({
      control1 = [-54.43, -109.519],
      control2 = [-152.916, -189.85],
      to = [-257.489, -249.236]
    }, %)
  |> bezierCurve({
      control1 = [-32.292, -12.323],
      control2 = [-76.12, -52.446],
      to = [-106.703, -17.791]
    }, %)
  |> bezierCurve({
      control1 = [3.298, -2.207],
      control2 = [31.567, 28.732],
      to = [39.881, 40.935]
    }, %)
  |> bezierCurve({
      control1 = [18.043, 27.056],
      control2 = [64.762, 54.808],
      to = [36.287, 90.981]
    }, %)
  |> bezierCurve({
      control1 = [-40.595, 24.762],
      control2 = [-74.945, -28.63],
      to = [-101.563, -52.634]
    }, %)
  |> bezierCurve({
      control1 = [-12.563, -26.581],
      control2 = [-37.888, -27.894],
      to = [-53.314, -2.655]
    }, %)
  |> close()
  |> hole(
        startSketchOn(XY)
  |> startProfileAt([133.985, 187.814], %)
    |> bezierCurve({
      control1 = [5.633, -0.181],
      control2 = [11.251, -0.904],
      to = [16.74, -2.187]
    }, %)
    |> bezierCurve({
      control1 = [49.47, -9.291],
      control2 = [76.165, -76.383],
      to = [42.383, -115.43]
    }, %)
    |> bezierCurve({
      control1 = [-34.586, -46.329],
      control2 = [-118.704, -34.43],
      to = [-135.898, 22.021]
    }, %)
    |> bezierCurve({
      control1 = [-16.288, 47.302],
      control2 = [26.994, 100.866],
      to = [76.775, 95.596]
    }, %)
    |> close(), %)

sketch002 = startSketchOn(XY)
  |> startProfileAt([123.725, 169.226], %)
  |> bezierCurve({
      control1 = [33.802, 5.369],
      control2 = [69.516, -24.881],
      to = [65.38, -59.918]
    }, %)
  |> bezierCurve({
      control1 = [-2.831, -45.665],
      control2 = [-66.251, -65.692],
      to = [-97.795, -35.12]
    }, %)
  |> bezierCurve({
      control1 = [-36.408, 28.479],
      control2 = [-12.83, 93.626],
      to = [32.415, 95.038]
    }, %)
  |> close()

sketch003 = startSketchOn(XY)
  |> startProfileAt([-329.459, -90.823], %)
  |> bezierCurve({
      control1 = [39.404, 72.468],
      control2 = [105.672, 135.135],
      to = [187.684, 154.45]
    }, %)
  |> bezierCurve({
      control1 = [9.929, 1.229],
      control2 = [20.054, 2.141],
      to = [30, 0.5]
    }, %)
  |> bezierCurve({
      control1 = [-17.86, -29.888],
      control2 = [-37.576, -59.002],
      to = [-50.3, -91.6]
    }, %)
  |> bezierCurve({
      control1 = [-64.505, -5.468],
      control2 = [-119.896, -45.96],
      to = [-162.053, -92.653]
    }, %)
  |> bezierCurve({
      control1 = [-21.163, -33.722],
      control2 = [-11.635, 15.213],
      to = [-5.331, 29.303]
    }, %)
  |> close()

sketch004 = startSketchOn(XY)
  |> startProfileAt([-235.515, -231.911], %)
  |> bezierCurve({
      control1 = [18.859, 21.101],
      control2 = [38.266, 41.703],
      to = [57.628, 62.341]
    }, %)
  |> bezierCurve({
      control1 = [50.286, 50.657],
      control2 = [93.436, 109.05],
      to = [150.712, 152.296]
    }, %)
  |> bezierCurve({
      control1 = [22.767, 7.796],
      control2 = [24.742, -17.043],
      to = [11.488, -28.977]
    }, %)
  |> bezierCurve({
      control1 = [-70.654, -64.942],
      control2 = [-146.483, -123.859],
      to = [-219.828, -185.66]
    }, %)
  |> close()

sketch005 = startSketchOn(XY)
  |> startProfileAt([-138.275, -331.974], %)
  |> bezierCurve({
      control1 = [50.313, 37.204],
      control2 = [98.997, 84.686],
      to = [114.534, 147.4]
    }, %)
  |> bezierCurve({
      control1 = [4.067, 39.107],
      control2 = [60.093, 36.041],
      to = [85.466, 60.6]
    }, %)
  |> bezierCurve({
      control1 = [5.316, 0.982],
      control2 = [9.273, 8.972],
      to = [14.989, 7.193]
    }, %)
  |> bezierCurve({
      control1 = [3.15, -46.522],
      control2 = [-24.008, -89.422],
      to = [-54.311, -122.693]
    }, %)
  |> bezierCurve({
      control1 = [-42.321, -45.045],
      control2 = [-95.987, -89.948],
      to = [-160.678, -92.5]
    }, %)
  |> close()

  sketch006 = startSketchOn(XY)
  |> startProfileAt([189.251, 282.776], %)
  |> bezierCurve({
      control1 = [45.587, 28.575],
      control2 = [98.649, 42.238],
      to = [151.468, 49.522]
    }, %)
  |> bezierCurve({
      control1 = [-5.446, -55.79],
      control2 = [-16.25, -111.406],
      to = [-36.495, -163.822]
    }, %)
  |> bezierCurve({
      control1 = [-38.325, 38.1],
      control2 = [-76.649, 76.2],
      to = [-114.973, 114.3]
    }, %)
  |> close()

```

### Expected Behavior

I expect that 'Top' should yield Y positive up, X positive to the right. I expect that 'Bottom' should yield Y positive up, X positive to the left.

### Screenshots and Recordings

https://kittycadworkspace.slack.com/files/U087Z76G206/F08GMQ72JN5/screenshare_-_2025-03-05_5_59_33_pm.mp4?origin_team=T025UH7US95&origin_channel=C06L2RHP9SL 

### Desktop OS

Windows 11

### Browser

Chrome

### Version

Multiple

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nickmccleery**
Closes #5654

### CODE REVIEW

**Comment by nickmccleery** [comment]
I've tried to keep change surface relatively small here, but think this should do what we want without going and fiddling too much with the other cases—especially if there's a revamp of all this stuff on the docket already.

File: src/clientSideScene/CameraControls.ts [hunk 1]
```diff
@@ -44,12 +47,21 @@ import {
   uuidv4,
 } from '@src/lib/utils'
 import { deg2Rad } from '@src/lib/utils2d'
-import type { SettingsType } from '@src/lib/settings/initialSettings'
 import { degToRad } from 'three/src/math/MathUtils'
 
+// Result type to make the linter happy.
+type Result<T, E = Error> = { ok: true; value: T } | { ok: false; error: E }
```
Comment (nadr0) [inline src/clientSideScene/CameraControls.ts]: I think we should use the helper library `@src/lib/trap` for this instead of reinventing a response since I think the one we have in the system should work. Let me post an example usage below.

File: src/clientSideScene/CameraControls.ts [hunk 2]
```diff
@@ -919,28 +931,132 @@ export class CameraControls {
     })
   }
 
+  async getCurrentView(): Promise<Result<CameraViewState_type, Error>> {
```
Comment (nadr0) [inline src/clientSideScene/CameraControls.ts]: `async getCurrentView(): Promise<CameraViewState_type | Error> {}`

Within `getCurrentView()` you can do

```
return new Error('my custom message')

or

return <A CameraViewState_type>
```

Then when used it should be

```
import { err } from '@src/lib/trap'

  const result = await getCurrentView()

  if (err(result)) {
    // Do something? err will auto print the value and result will be of type Error
  }
```

For an example within the code base you can look at the function `doPromptEdit` and it should show usage of this pattern.

File: src/clientSideScene/CameraControls.ts (hunk 1 above)
Comment (nickmccleery) [reply src/clientSideScene/CameraControls.ts]: Ah nice, didn't know we had such a thing.

File: src/clientSideScene/CameraControls.ts [hunk 3]
```diff
@@ -919,28 +931,132 @@ export class CameraControls {
...
+    // The approach first retrieves current camera setup, then alters pivot params,
+    // ultimately preserving other camera settings, e.g., ortho vs. perspective projection.
+
+    // Note: this assumes right handed, Z-up, X positive to the right.
+    const Z_AXIS_QUATERNIONS = {
+      [StandardView.TOP]: { x: 0, y: 0, z: 0, w: 1 },
+      [StandardView.BOTTOM]: { x: 1, y: 0, z: 0, w: 0 },
+    } as const
+
+    const currentViewResult = await this.getCurrentView()
```
Comment (nadr0) [inline src/clientSideScene/CameraControls.ts]: food for thought, this does not need to be changed. Devs usually use these several variable names `currentPosition`, `lastPosition`, `prevPosition`, `nextPosition` etc...

I have been using the pattern `position` and `requestedPosition`

```
function setPosition(requestedPosition: Vector3) : void {
   const position = this.getPosition() // my current position it is the position
   position.set(requestedPosition)
}
```

The mental model is the noun is always the current, you don't need `currentPosition` because current is redundant. What is my position? Your position is position!

Inside the function that has to do the business logic it is trying to request a new position. Instead of `newPosition` I use the word requested because the function does not need to set the position. It is requesting it.


```
function setPosition(requestedPosition: Vector3) : void {
   const position = this.getPosition() // my current position it is the position
   const date = this.getDate()

   if (date === 'Tuesday') {
     position.set(requestedPosition)
   }
   
}
```

Obviously this is an awful function but builds a mental model that `setPosition` does not need to set the position, you the dev are requesting the "system" to set the position so when you talk about "where am I?" and "where am I going?" the variable names are clearer (imo)

---


- `currPos`
- `nextPos`
- `prevPos`
- `lastPos`
- `newPos`
^ this shit can drive me crazy some times.

I like asking the question
- Where am I / What do I have?
- Where am I going?

You have `position` and you are trying to go to `requestedPosition`. 

Last point, when you think of `requestedPosition` it implies that it could fail and not be set. When you use `nextPosition` you assume it will always succeed in being the following value. 

When being web systems, making API calls, managing complex application state sometimes the thing you request may not be applied.

Comment (nickmccleery) [reply src/clientSideScene/CameraControls.ts]: Nah I'm happy to engage haha. Aside from not really feeling this is 'my' codebase, I like these discussions—though I don't have a super strong preference here.

I find your argument intellectually appealing, but generally also index super hard on removing ambiguity. If you can have a moving position and you care about its previous and future conditions, I think having the (tautological) `current` clarification isn't bad; it makes it clear to the reader what the desire was, even if it's completely redundant.

So I agree with the principle, and on an intellectual level, but I don't find seeing `currentThing` upsetting...  because I find it incredibly clear (and definitely produce `currentThing` variables on a regular basis myself).

That said, pinching some convention from the physical world, I've gone with `cameraView` and `cameraViewTarget`. Hopefully unambiguous and still demarcates what we want to have from what we (currently) have.

File: src/clientSideScene/CameraControls.ts (hunk 2 above)
Comment (nickmccleery) [reply src/clientSideScene/CameraControls.ts]: Nice. I've gone `async getCameraView(): Promise<CameraViewState_type | Error>` and dumped in the `err` bubbler

File: src/clientSideScene/CameraControls.ts [hunk 4]
```diff
@@ -919,28 +929,124 @@ export class CameraControls {
...
+    // Note: this assumes right handed, Z-up, X positive to the right.
+    const Z_AXIS_QUATERNIONS = {
+      [StandardView.TOP]: { x: 0, y: 0, z: 0, w: 1 },
+      [StandardView.BOTTOM]: { x: 1, y: 0, z: 0, w: 0 },
+    } as const
+
+    const cameraView = await this.getCameraView()
+
+    if (err(cameraView)) {
+      console.error(cameraView.message)
```
Comment (nadr0) [inline src/clientSideScene/CameraControls.ts]: You don't need to relog it here, the function `err` will console error it for you.

Comment (nickmccleery) [reply src/clientSideScene/CameraControls.ts]: Ah so it does, removed.

**Review by nadr0 — APPROVED** [review]
Thanks for addressing all the comments. I ran this locally to test the functionality and the basis coordinate appears to be working properly.

I used the axis dots to look down the axis, I used the dropdown menu next to the gizmo, I also used the native file menu for `Standard Views` and they all worked well.
