### PR TITLE
Refactor boolean codemods and fix two selection bugs

### LINKED ISSUE #7669: Bug: Selecting bodies from a multi-profile extrude as Substract tools leads to a KCL error
> Oh that's a fun point-and-click codemod bug (for me haha). Since the multi-profile extrude is only assigned to one variable, when selecting the two bodies it generated for the substract op, it resolved to the array `[extrude002, extrude002]` which.. failed successfully

[Slack Message](https://kittycadworkspace.slack.com/archives/C06L2RHP9SL/p1751464729428559?thread_ts=1751464729.428559&cid=C06L2RHP9SL)

### PR DESCRIPTION
**Pull request by pierremtb**
Fixes #7669 and #7567 by refactoring the boolean codemods to follow the changes done for sweeps and transforms.

### CODE REVIEW

File: src/lang/modifyAst/boolean.ts [hunk 1]
```diff
@@ -1,331 +1,182 @@
...
   }
 
-  return lastVars
-}
-
-/** returns all children of a given artifact, and sorts them DESC by start sourceRange
- * The usecase is we want the last declare relevant  child to use in the boolean operations
- * but might be useful else where.
- */
-export function findAllChildrenAndOrderByPlaceInCode(
```
Comment (pierremtb) [inline src/lang/modifyAst/boolean.ts:150]: This and getLastVariable were moved as-is to `src/lang/queryAst.ts`

File: src/lang/modifyAst/boolean.ts [hunk 2]
```diff
@@ -1,331 +1,182 @@
...
-  dependencies: {
-    kclManager: KclManager
-    engineCommandManager: EngineCommandManager
-    codeManager: CodeManager
-    editorManager: EditorManager
-  }
-): Promise<Error | void> {
-  const ast = dependencies.kclManager.ast
-  const lastSolidsVars = getLastVariableDeclarationsFromSelections(
+export function addUnion({
```
Comment (pierremtb) [inline src/lang/modifyAst/boolean.ts:17]: Here just renaming like sweeps and transforms with the same ins and outs. No unit testing here because we still have one pw test per codemod, but as soon as we wire edit flows (not needed yet but I did put in the nodeToEdit arg) or add new unlabeled args, we should move tests to a `boolean.test.ts` file

File: src/lang/queryAst.ts [hunk 3]
```diff
@@ -1396,3 +1397,119 @@ export const getPathNormalisedForTruncatedAst = (
     Number(nodePathWithCorrectedIndexForTruncatedAst[1][0]) - minIndex
   return nodePathWithCorrectedIndexForTruncatedAst
 }
+
```
Comment (pierremtb) [inline src/lang/queryAst.ts:1396]: These functions are just copied as-is from boolean.ts, except for an added case below

File: src/lang/modifyAst/boolean.ts [hunk 4]
```diff
@@ -1,331 +1,182 @@
...
-      varDecs.map((varDec) => createLocalName(varDec.declaration.id.name))
-    )
-  const solidsArrayExpression = createArrExpr(solids)
+  const call = createCallExpressionStdLibKw('subtract', objectsExpr, [
+    createLabeledArg('tools', toolsExpr),
+  ])
+
+  // 3. If edit, we assign the new function call declaration to the existing node,
+  // otherwise just push to the end
+  const pathToNode = setCallInAst({
```
Comment (pierremtb) [inline src/lang/modifyAst/boolean.ts:174]: Calling this util function here makes sure we don't get two identical variables for multi extrude selection #7669. There's an existing unit test for that added earlier.

File: src/lang/queryAst.ts [hunk 5]
```diff
@@ -1396,3 +1397,119 @@ export const getPathNormalisedForTruncatedAst = (
...
+    } else if (current?.type === 'edgeCut') {
+      pushToSomething(currentId, current.surfaceId)
+    } else if (current?.type === 'startSketchOnPlane') {
+      pushToSomething(currentId, current.planeId)
+    } else if (current?.type === 'plane') {
+      pushToSomething(currentId, current.pathIds)
+    } else if (current?.type === 'compositeSolid') {
+      pushToSomething(currentId, current.solidIds)
+      pushToSomething(currentId, current.toolIds)
+    }
```
Comment (pierremtb) [inline src/lang/queryAst.ts:1468]: Actually not as-is: this added case here on `compositeSolid` makes it possible to do a bool op on a bool op result. I should probably add a test for this

File: src/lib/commandBarConfigs/modelingCommandConfig.ts [hunk 6]
```diff
@@ -618,20 +629,18 @@ export const modelingMachineCommandConfig: StateMachineCommandSetConfig<
...
         // Issue link: https://github.com/KittyCAD/engine/issues/3435
         multiple: false,
         required: true,
         hidden: (context) => Boolean(context.argumentsToSubmit.nodeToEdit),
       },
       tools: {
-        clearSelectionFirst: true,
+        ...objectsTypesAndFilters,
         inputType: 'selection',
-        selectionTypes: ['path'],
```
Comment (pierremtb) [inline src/lib/commandBarConfigs/modelingCommandConfig.ts:633]: Not having `'sweep'` here was limiting the ability to select the loft for #7567. This works now

File: src/lang/modifyAst/boolean.ts [hunk 7]
```diff
@@ -1,331 +1,182 @@
...
+    ast: modifiedAst,
+    call,
+    pathToEdit: nodeToEdit,
+    pathIfNewPipe: vars.pathIfPipe,
```
Comment (pierremtb) [inline src/lang/modifyAst/boolean.ts]: Shoot I should probably make sure that solids and tools aren't conflicting here

Comment (pierremtb) [reply src/lang/modifyAst/boolean.ts]: Made the change
