### PR TITLE
Stop guarding on KCL errors: let people point-and-click a fix

### LINKED ISSUE #6297: use artifact graph we get back on errors to do selections on whatever did work
more context here: https://kittycadworkspace.slack.com/archives/C04KFV6NKL0/p1744408040947259

### PR DESCRIPTION
**Pull request by pierremtb**
Closes #6297

Context and initial proposed solution by @jtran at https://github.com/KittyCAD/modeling-app/issues/6297#issuecomment-3416254629

Would be good to have people play with this before merging. I personally like it a lot but would love to get more feedback.

https://github.com/user-attachments/assets/626e2d56-3fe9-4cb1-8759-4b020a3cd0b6

### CODE REVIEW

File: src/machines/modelingMachine.ts [hunk 1]
```diff
@@ -4220,150 +4217,120 @@ export const modelingMachine = setup({
...
             ],
-            guard: 'no kcl errors',
           },
         ],
 
+        // Modeling codemods
+
         Extrude: {
           target: 'Applying extrude',
-          reenter: true,
```
Comment (pierremtb) [inline src/machines/modelingMachine.ts:4229]: Unclear to me if `reenter: true` was doing anything here, I'm not seeing any side effect when removing it.

File: src/machines/modelingMachine.ts [hunk 2]
```diff
@@ -4220,150 +4217,120 @@ export const modelingMachine = setup({
...
-        },
-
-        'Text-to-CAD': {
-          target: 'idle',
-          reenter: false,
-          actions: ['Submit to Text-to-CAD API'],
-        },
-
-        'Prompt-to-edit': 'Applying Prompt-to-edit',
```
Comment (pierremtb) [inline src/machines/modelingMachine.ts:4309]: Moving those guys down a bit so modeling codemods are all together

**Comment by jtran** [comment]
Code looks good. I can try checking it out and running it tomorrow.

**Comment by jtran** [comment]
Could the "has error" label go inside the box? Screenshot isn't showing the hover border. Currently, I can't click the label, even though when I right-click on it, it says I can double-click.

Screenshot 2025-11-04 at 9 40 48 AM

**Comment by pierremtb** [comment]
@jtran this is what you mean yes? 

image

**Comment by pierremtb** [comment]
@jtran Good find, fixed it with https://github.com/kittycad/modeling-app/commit/1bb75072dc965b8a815536073ec19fa77e416037

**Review by jtran — APPROVED** [review]

File: src/machines/modelingMachine.ts (hunk 1 above)
Comment (franknoirot) [reply src/machines/modelingMachine.ts:4229]: `reenter: true` will make a transition fire `onExit` and `onEnter` actions even on the actor and current state node (docs [here](https://stately.ai/docs/transitions#re-entering)), so these had no effect.

**Review by franknoirot — APPROVED** [review]
This is much better user experience thank you for pulling this through @pierremtb. Now all we need is to show users that their chamfer is too big or whatever in the feature tree and we'll be cruising.
